package com.digitalpen.auriont8i;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.provider.OpenableColumns;import android.database.Cursor;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity{
 LinearLayout root,content,tools,film,quick;ImageView preview;TextView status,info,hist;Uri current;Bitmap source,maskBitmap;ArrayList<Uri> library=new ArrayList<>();int selected=0;int cyan=Color.rgb(0,210,255),violet=Color.rgb(130,55,255),magenta=Color.rgb(255,35,180),bg=Color.rgb(3,3,7),panel=Color.rgb(13,13,20);int pending=0;HashMap<String,Integer> vals=new HashMap<>();
 String active="REVELAÇÃO";ArrayList<HashMap<String,Integer>> history=new ArrayList<>();int historyPos=-1;
 public void onCreate(Bundle b){super.onCreate(b);for(String k:new String[]{"exposure","contrast","sat","temp","tint","bright","sharp","red","green","blue","fade","curve","shadow","mid","highlight","mask","vignette","grain","hRed","hOrange","hYellow","hGreen","hCyan","hBlue","hPurple","hMagenta"})vals.put(k,50);build();}
 GradientDrawable quantum(){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{violet,magenta,Color.rgb(55,85,255),cyan});g.setCornerRadius(24);return g;}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(14,10,14,10);return v;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setTextColor(Color.WHITE);GradientDrawable g=new GradientDrawable();g.setColor(panel);g.setStroke(2,Color.rgb(95,55,180));g.setCornerRadius(24);x.setBackground(g);x.setAllCaps(false);x.setPadding(18,4,18,4);return x;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.BLACK,Color.rgb(7,7,7),Color.BLACK}));setContentView(root);
 LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView h=t("☰   AURION T8i",18);h.setTextColor(Color.WHITE);top.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView actions=t("⌕   ☁   ⚙",18);actions.setTextColor(cyan);top.addView(actions);root.addView(top);View glow=new View(this);glow.setBackground(quantum());root.addView(glow,new LinearLayout.LayoutParams(-1,4));status=t("QUANTUM PHOTO STUDIO · BLUEPRINT TEST 01 · v0.10",10);status.setTextColor(Color.LTGRAY);root.addView(status);quick=new LinearLayout(this);quick.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);TextView edit=t("EDIÇÃO",11);edit.setTextColor(Color.LTGRAY);quick.addView(edit,new LinearLayout.LayoutParams(0,-2,1));Button qu=b("↶");qu.setOnClickListener(v->undo());quick.addView(qu);Button qr=b("↷");qr.setOnClickListener(v->redo());quick.addView(qr);TextView qh=t(" HIST 0 ",11);qh.setTag("historyCount");quick.addView(qh);root.addView(quick);
 HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout nav=new LinearLayout(this);String[] ns={"▣\\nFotos","☼\\nLuz","◉\\nCor","HSL\\nMix","◒\\nRoda","⌁\\nCurvas","◌\\nMáscara","△\\nDetalhe","✦\\nEfeitos","A\\nAuto","⇄\\nConverter","⇧\\nExportar","⋯\\nLab"};
 for(String n:ns){Button x=b(n);x.setOnClickListener(v->{String z=((Button)v).getText().toString();if(z.contains("FOTOS"))z="BIBLIOTECA";else if(z.contains("LUZ"))z="LUZ";else if(z.contains("COR")&&!z.contains("HSL"))z="COR";else if(z.contains("RODA"))z="RODA";else if(z.contains("CURVAS"))z="CURVAS";else if(z.contains("MÁSCARA"))z="MÁSCARA";else if(z.contains("DETALHE"))z="DETALHE";else if(z.contains("EFEITOS"))z="EFEITOS";else if(z.contains("CONVERTER"))z="CONVERSOR";else if(z.contains("EXPORTAR"))z="ENTREGA";open(z);});nav.addView(x);}hs.addView(nav);root.addView(hs);
 content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(10,8,10,8);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));
 preview=new ImageView(this);preview.setBackgroundColor(Color.BLACK);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setOnTouchListener((v,e)->previewTouch(e));content.addView(preview,new LinearLayout.LayoutParams(-1,0,1));
 info=t("Importe JPG, PNG ou WebP para editar.",11);content.addView(info);hist=t("RGB  HISTOGRAMA",10);hist.setTextColor(Color.WHITE);hist.setBackgroundColor(Color.rgb(5,5,5));content.addView(hist); film=new LinearLayout(this);film.setOrientation(LinearLayout.HORIZONTAL);film.setBackgroundColor(Color.rgb(8,8,8));HorizontalScrollView fs=new HorizontalScrollView(this);fs.setHorizontalScrollBarEnabled(false);fs.addView(film);content.addView(fs,new LinearLayout.LayoutParams(-1,92));
 tools=new LinearLayout(this);tools.setOrientation(LinearLayout.VERTICAL);tools.setBackgroundColor(Color.rgb(9,9,14));content.addView(tools);
 HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout nav=new LinearLayout(this);nav.setPadding(6,5,6,5);String[] ns={"▣
Fotos","☼
Luz","◉
Cor","HSL
Mix","◒
Roda","⌁
Curvas","◌
Máscara","△
Detalhe","✦
Efeitos","A
Auto","⇄
Converter","⇧
Exportar","⋯
Lab"};
 for(String n:ns){Button x=b(n);x.setTextSize(10);x.setMinWidth(105);x.setOnClickListener(v->{String z=((Button)v).getText().toString();if(z.contains("Fotos"))z="BIBLIOTECA";else if(z.contains("Luz"))z="LUZ";else if(z.contains("Cor"))z="COR";else if(z.contains("Mix"))z="HSL";else if(z.contains("Roda"))z="RODA";else if(z.contains("Curvas"))z="CURVAS";else if(z.contains("Máscara"))z="MÁSCARA";else if(z.contains("Detalhe"))z="DETALHE";else if(z.contains("Efeitos"))z="EFEITOS";else if(z.contains("Auto"))z="AUTO";else if(z.contains("Converter"))z="CONVERSOR";else if(z.contains("Exportar"))z="ENTREGA";else z="LAB";open(z);});nav.addView(x,new LinearLayout.LayoutParams(112,86));}hs.addView(nav);root.addView(hs,new LinearLayout.LayoutParams(-1,96));open("REVELAÇÃO");}
 void open(String n){active=n;tools.removeAllViews();status.setText("AURION · "+n+" · edição local");
 if(n.equals("BIBLIOTECA")){Button x=b("IMPORTAR ARQUIVO");x.setOnClickListener(v->pick());tools.addView(x);}
 else if(n.equals("REVELAÇÃO")||n.equals("LUZ")){slider("Exposição","exposure");slider("Brilho","bright");slider("Contraste","contrast");Button r=b("RESET");r.setOnClickListener(v->reset());tools.addView(r);}
 else if(n.equals("COR")){slider("Temperatura","temp");slider("Matiz","tint");slider("Saturação","sat");slider("Desvanecer","fade");}
 else if(n.equals("HSL")){slider("Vermelho","hRed");slider("Laranja","hOrange");slider("Amarelo","hYellow");slider("Verde","hGreen");slider("Ciano","hCyan");slider("Azul","hBlue");slider("Roxo","hPurple");slider("Magenta","hMagenta");}
 else if(n.equals("RODA")){colorWheel();slider("Vermelho","red");slider("Verde","green");slider("Azul","blue");slider("Sombras","shadow");slider("Médios","mid");slider("Realces","highlight");}
 else if(n.equals("CURVAS")){curveView();slider("Curva tonal","curve");}
 else if(n.equals("MÁSCARA")){Button m=b("PINCEL DE MÁSCARA · DESENHE SOBRE A FOTO");m.setOnClickListener(v->{status.setText("MÁSCARA ATIVA · pinte diretamente na fotografia");});tools.addView(m);slider("Força local","mask");Button cl=b("LIMPAR MÁSCARA");cl.setOnClickListener(v->{maskBitmap=null;render();snapshot("Limpar máscara");});tools.addView(cl);}
 else if(n.equals("DETALHE")){slider("Nitidez","sharp");}
 else if(n.equals("EFEITOS")){slider("Vinheta","vignette");slider("Grão","grain");}
 else if(n.equals("ANTES/DEPOIS")){Button a=b("SEGURE PARA VER O ANTES");a.setOnTouchListener((v,e)->{if(source==null)return true;if(e.getAction()==MotionEvent.ACTION_DOWN){preview.clearColorFilter();preview.setImageBitmap(source);status.setText("ANTES · original");}else if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL){render();status.setText("DEPOIS · edição atual");}return true;});tools.addView(a);}

 else if(n.equals("AUTO")){Button x=b("ANALISAR E APLICAR AUTO");x.setOnClickListener(v->auto());tools.addView(x);}
 else if(n.equals("CONVERSOR")){Button j=b("CONVERTER → JPEG");j.setOnClickListener(v->save(0));tools.addView(j);Button p=b("CONVERTER → PNG");p.setOnClickListener(v->save(1));tools.addView(p);Button w=b("CONVERTER → WEBP");w.setOnClickListener(v->save(2));tools.addView(w);}
 else if(n.equals("ENTREGA")){Button x=b("EXPORTAR MASTER");x.setOnClickListener(v->chooseMaster());tools.addView(x);}
 else if(n.equals("LAB")){TextView q=t(source==null?"Sem imagem carregada.":"Imagem: "+source.getWidth()+"×"+source.getHeight()+"
Memória bitmap: "+source.getByteCount()/1024+" KB
Engine: Android Bitmap/Canvas
Processamento: local/offline",12);tools.addView(q);}
 }
 boolean previewTouch(MotionEvent e){if(source==null)return true;if(active.equals("MÁSCARA")){if(maskBitmap==null)maskBitmap=Bitmap.createBitmap(source.getWidth(),source.getHeight(),Bitmap.Config.ALPHA_8);if(e.getAction()==MotionEvent.ACTION_DOWN||e.getAction()==MotionEvent.ACTION_MOVE){float sx=source.getWidth()/(float)Math.max(1,preview.getWidth()),sy=source.getHeight()/(float)Math.max(1,preview.getHeight());Canvas mc=new Canvas(maskBitmap);Paint mp=new Paint(1);mp.setColor(Color.WHITE);mc.drawCircle(e.getX()*sx,e.getY()*sy,Math.max(30,source.getWidth()/25f),mp);status.setText("MÁSCARA · pintando");}else if(e.getAction()==MotionEvent.ACTION_UP)snapshot("Máscara pintada");return true;}if(e.getAction()==MotionEvent.ACTION_DOWN){preview.clearColorFilter();preview.setImageBitmap(source);status.setText("ANTES · segure para comparar");}else if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL){render();status.setText("DEPOIS · edição atual");}return true;}
 void undo(){if(historyPos>0){historyPos--;vals.clear();vals.putAll(history.get(historyPos));render();updateHistoryCount();}}void redo(){if(historyPos<history.size()-1){historyPos++;vals.clear();vals.putAll(history.get(historyPos));render();updateHistoryCount();}}void updateHistoryCount(){if(quick!=null){View v=quick.findViewWithTag("historyCount");if(v instanceof TextView)((TextView)v).setText(" HIST "+Math.max(0,historyPos)+" ");}}
 void colorWheel(){ImageView w=new ImageView(this);Bitmap b=Bitmap.createBitmap(520,360,Bitmap.Config.ARGB_8888);Canvas cc=new Canvas(b);Paint p=new Paint(1);float cx=260,cy=180;for(int a=0;a<360;a++){p.setColor(Color.HSVToColor(new float[]{a,1,1}));cc.drawArc(cx-145,cy-145,cx+145,cy+145,a,2,true,p);}RadialGradient white=new RadialGradient(cx,cy,145,new int[]{Color.WHITE,Color.TRANSPARENT},null,Shader.TileMode.CLAMP);p.setShader(white);cc.drawCircle(cx,cy,145,p);p.setShader(null);w.setImageBitmap(b);w.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN||e.getAction()==MotionEvent.ACTION_MOVE){float dx=e.getX()-v.getWidth()/2f,dy=e.getY()-v.getHeight()/2f;float hue=(float)Math.toDegrees(Math.atan2(dy,dx));if(hue<0)hue+=360;float rad=Math.min(1f,(float)Math.sqrt(dx*dx+dy*dy)/(Math.min(v.getWidth(),v.getHeight())*.48f));int col=Color.HSVToColor(new float[]{hue,rad,1});vals.put("red",Math.max(0,Math.min(100,50+(Color.red(col)-128)/5)));vals.put("green",Math.max(0,Math.min(100,50+(Color.green(col)-128)/5)));vals.put("blue",Math.max(0,Math.min(100,50+(Color.blue(col)-128)/5)));render();}else if(e.getAction()==MotionEvent.ACTION_UP)snapshot("Roda de cor");return true;});tools.addView(w,new LinearLayout.LayoutParams(-1,360));}
 void curveView(){ImageView w=new ImageView(this);Bitmap b=Bitmap.createBitmap(420,180,Bitmap.Config.ARGB_8888);Canvas cc=new Canvas(b);Paint g=new Paint(1);g.setColor(Color.DKGRAY);for(int i=0;i<=4;i++){cc.drawLine(i*105,0,i*105,180,g);cc.drawLine(0,i*45,420,i*45,g);}Paint p=new Paint(1);p.setColor(cyan);p.setStrokeWidth(5);Path q=new Path();q.moveTo(0,180);q.cubicTo(110,155,285,30,420,0);cc.drawPath(q,p);w.setImageBitmap(b);w.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN||e.getAction()==MotionEvent.ACTION_MOVE){int val=Math.max(0,Math.min(100,Math.round(100*(1-e.getY()/v.getHeight()))));vals.put("curve",val);render();}else if(e.getAction()==MotionEvent.ACTION_UP)snapshot("Curva tonal");return true;});tools.addView(w,new LinearLayout.LayoutParams(-1,240));}
 void slider(String label,String key){LinearLayout r=new LinearLayout(this);r.setPadding(8,2,8,2);r.setGravity(Gravity.CENTER_VERTICAL);TextView l=t(label,11);r.addView(l,new LinearLayout.LayoutParams(0,-2,.3f));SeekBar s=new SeekBar(this);s.setMax(100);s.setProgress(vals.get(key));s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar z,int p,boolean f){vals.put(key,p);render();}public void onStartTrackingTouch(SeekBar z){}public void onStopTrackingTouch(SeekBar z){snapshot(label);}});r.addView(s,new LinearLayout.LayoutParams(0,-2,.7f));tools.addView(r);}
 void snapshot(String label){while(history.size()>historyPos+1)history.remove(history.size()-1);history.add(new HashMap<>(vals));historyPos=history.size()-1;status.setText(label+" · alteração registrada");updateHistoryCount();}
 
 void reset(){for(String k:vals.keySet())vals.put(k,50);open(active);render();status.setText("Ajustes zerados");}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,10);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==10){library.clear();if(d.getClipData()!=null){for(int i=0;i<d.getClipData().getItemCount();i++)library.add(d.getClipData().getItemAt(i).getUri());}else if(d.getData()!=null)library.add(d.getData());for(Uri u:library){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}}selected=0;if(!library.isEmpty()){current=library.get(0);load();refreshFilm();status.setText(library.size()+" arquivo(s) carregado(s) · toque nas miniaturas");}}else if(r==20)export(d.getData());}
 String name(Uri u){try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Exception e){}return "foto";}
 void refreshFilm(){film.removeAllViews();for(int i=0;i<library.size();i++){final int ix=i;ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setPadding(4,4,4,4);try(InputStream z=getContentResolver().openInputStream(library.get(i))){BitmapFactory.Options op=new BitmapFactory.Options();op.inSampleSize=16;Bitmap th=BitmapFactory.decodeStream(z,null,op);if(th!=null)im.setImageBitmap(th);}catch(Exception e){}GradientDrawable gd=new GradientDrawable();gd.setColor(Color.rgb(12,13,24));gd.setStroke(i==selected?5:2,i==selected?violet:cyan);gd.setCornerRadius(18);im.setBackground(gd);im.setOnClickListener(v->{selected=ix;current=library.get(ix);load();refreshFilm();});film.addView(im,new LinearLayout.LayoutParams(104,82));}}
 void load(){history.clear();historyPos=-1;try(InputStream in=getContentResolver().openInputStream(current)){source=BitmapFactory.decodeStream(in);if(source==null){status.setText("Formato sem decoder nesta build");return;}info.setText(name(current)+" · "+source.getWidth()+"×"+source.getHeight());render();calcHist();snapshot("Original");status.setText("Imagem carregada · histórico iniciado");}catch(Exception e){status.setText("Erro: "+e.getMessage());}}
 ColorMatrix matrix(){float ev=(vals.get("exposure")-50)/50f,br=(vals.get("bright")-50)*2f,co=(vals.get("contrast")-50)/50f+1f,sa=vals.get("sat")/50f,te=(vals.get("temp")-50)*1.5f,ti=(vals.get("tint")-50)*1.2f,sc=(float)Math.pow(2,ev),off=128*(1-co)+br,rg=vals.get("red")/50f,gg=vals.get("green")/50f,bg=vals.get("blue")/50f,fade=(vals.get("fade")-50)*0.7f;ColorMatrix m=new ColorMatrix(new float[]{sc*co*rg,0,0,0,off+te+ti+fade,0,sc*co*gg,0,0,off-ti+fade,0,0,sc*co*bg,0,off-te+ti+fade,0,0,0,1,0});ColorMatrix sm=new ColorMatrix();sm.setSaturation(sa);m.postConcat(sm);float cv=(vals.get("curve")-50)/100f;if(cv!=0){ColorMatrix cm=new ColorMatrix(new float[]{1+cv,0,0,0,-128*cv,0,1+cv,0,0,-128*cv,0,0,1+cv,0,-128*cv,0,0,0,1,0});m.postConcat(cm);}return m;}
 boolean hslChanged(){for(String k:new String[]{"hRed","hOrange","hYellow","hGreen","hCyan","hBlue","hPurple","hMagenta"})if(vals.get(k)!=50)return true;return false;}
 int hueBand(float h){if(h<15||h>=345)return 0;if(h<45)return 1;if(h<75)return 2;if(h<165)return 3;if(h<195)return 4;if(h<255)return 5;if(h<300)return 6;return 7;}
 String hueKey(int b){return new String[]{"hRed","hOrange","hYellow","hGreen","hCyan","hBlue","hPurple","hMagenta"}[b];}
 Bitmap applyHsl(Bitmap in){if(!hslChanged())return in;int w=in.getWidth(),h=in.getHeight();Bitmap o=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);int[] px=new int[w];float[] hsv=new float[3];for(int y=0;y<h;y++){in.getPixels(px,0,w,0,y,w,1);for(int x=0;x<w;x++){int a=Color.alpha(px[x]);Color.colorToHSV(px[x],hsv);int v=vals.get(hueKey(hueBand(hsv[0])))-50;if(v!=0){hsv[1]=Math.max(0f,Math.min(1f,hsv[1]*(1f+v/50f)));hsv[2]=Math.max(0f,Math.min(1f,hsv[2]*(1f+v/125f)));}px[x]=Color.HSVToColor(a,hsv);}o.setPixels(px,0,w,0,y,w,1);}return o;}
 void render(){if(source==null)return;if(hslChanged()){Bitmap h=applyHsl(source);preview.clearColorFilter();Bitmap o=Bitmap.createBitmap(h.getWidth(),h.getHeight(),Bitmap.Config.ARGB_8888);Canvas c=new Canvas(o);Paint p=new Paint(Paint.FILTER_BITMAP_FLAG);p.setColorFilter(new ColorMatrixColorFilter(matrix()));c.drawBitmap(h,0,0,p);preview.setImageBitmap(o);if(h!=source)h.recycle();}else{preview.setImageBitmap(source);preview.setColorFilter(new ColorMatrixColorFilter(matrix()));}}
 Bitmap rendered(){if(source==null)return null;Bitmap base=applyHsl(source);Bitmap o=Bitmap.createBitmap(source.getWidth(),source.getHeight(),Bitmap.Config.ARGB_8888);Canvas c=new Canvas(o);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);p.setColorFilter(new ColorMatrixColorFilter(matrix()));c.drawBitmap(base,0,0,p);if(base!=source)base.recycle();int vig=vals.get("vignette")-50;if(vig>0){Paint vp=new Paint();RadialGradient rgd=new RadialGradient(source.getWidth()/2f,source.getHeight()/2f,Math.max(source.getWidth(),source.getHeight())*.7f,new int[]{Color.TRANSPARENT,Color.argb(Math.min(190,vig*3),0,0,0)},null,Shader.TileMode.CLAMP);vp.setShader(rgd);c.drawRect(0,0,source.getWidth(),source.getHeight(),vp);}int sh=vals.get("sharp")-50;if(sh>3){Paint edge=new Paint();edge.setAlpha(Math.min(80,sh));edge.setColorFilter(new ColorMatrixColorFilter(new ColorMatrix(new float[]{1.2f,0,0,0,-20,0,1.2f,0,0,-20,0,0,1.2f,0,-20,0,0,0,1,0})));c.drawBitmap(o,0,0,edge);}return o;}
 void calcHist(){if(source==null)return;int[] bins=new int[16],rr=new int[16],gg=new int[16],bb=new int[16];int sx=Math.max(1,source.getWidth()/160),sy=Math.max(1,source.getHeight()/160);long sum=0,n=0;for(int y=0;y<source.getHeight();y+=sy)for(int x=0;x<source.getWidth();x+=sx){int c=source.getPixel(x,y),v=(Color.red(c)+Color.green(c)+Color.blue(c))/3;bins[Math.min(15,v/16)]++;rr[Math.min(15,Color.red(c)/16)]++;gg[Math.min(15,Color.green(c)/16)]++;bb[Math.min(15,Color.blue(c)/16)]++;sum+=v;n++;}StringBuilder s=new StringBuilder("HIST ");int mx=1;for(int v:bins)mx=Math.max(mx,v);String chars="▁▂▃▄▅▆▇█";for(int v:bins)s.append(chars.charAt(Math.min(7,v*8/mx)));s.append("  Luma ").append(n==0?0:sum/n);Bitmap hb=Bitmap.createBitmap(480,100,Bitmap.Config.ARGB_8888);Canvas hc=new Canvas(hb);int max=1;for(int i=0;i<16;i++)max=Math.max(max,Math.max(rr[i],Math.max(gg[i],bb[i])));Paint hp=new Paint(1);hp.setStrokeWidth(3);int[] cs={Color.RED,Color.GREEN,Color.BLUE};int[][] ar={rr,gg,bb};for(int k=0;k<3;k++){hp.setColor(cs[k]);for(int i=1;i<16;i++)hc.drawLine((i-1)*32,100-ar[k][i-1]*95/max,i*32,100-ar[k][i]*95/max,hp);}hist.setText("HISTOGRAMA RGB · Luma "+(n==0?0:sum/n));hist.setCompoundDrawablesWithIntrinsicBounds(null,new BitmapDrawable(getResources(),hb),null,null);}
 void auto(){if(source==null){status.setText("Importe uma imagem primeiro");return;}int sx=Math.max(1,source.getWidth()/100),sy=Math.max(1,source.getHeight()/100);long sum=0,n=0;for(int y=0;y<source.getHeight();y+=sy)for(int x=0;x<source.getWidth();x+=sx){int c=source.getPixel(x,y);sum+=(Color.red(c)+Color.green(c)+Color.blue(c))/3;n++;}float mean=n==0?128:(float)sum/n;vals.put("exposure",Math.max(35,Math.min(65,50+Math.round((128-mean)/12))));vals.put("contrast",54);vals.put("sat",52);render();calcHist();status.setText("AUTO analisou luminância · ajustes conservadores aplicados");}
 void chooseMaster(){if(source==null){status.setText("Importe uma imagem primeiro");return;}final String[] a={"JPEG 100%","PNG lossless","WEBP lossless"};new AlertDialog.Builder(this).setTitle("ENTREGA MASTER").setItems(a,(d,w)->save(w)).show();}
 void save(int type){if(source==null){status.setText("Importe uma imagem primeiro");return;}pending=type;String mime=type==1?"image/png":type==2?"image/webp":"image/jpeg",ext=type==1?".png":type==2?".webp":".jpg";Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);i.putExtra(Intent.EXTRA_TITLE,"AURION_"+System.currentTimeMillis()+ext);startActivityForResult(i,20);}
 void export(Uri u){Bitmap o=rendered();try(OutputStream os=getContentResolver().openOutputStream(u)){Bitmap.CompressFormat f=pending==1?Bitmap.CompressFormat.PNG:pending==2?Bitmap.CompressFormat.WEBP_LOSSLESS:Bitmap.CompressFormat.JPEG;if(o.compress(f,100,os))status.setText("Arquivo convertido/exportado com sucesso");else status.setText("Falha no codec");}catch(Exception e){status.setText("Erro: "+e.getMessage());}finally{if(o!=null)o.recycle();}}
}