package com.digitalpen.auriont8i;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.provider.OpenableColumns;import android.database.Cursor;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity{
 LinearLayout root,content,tools,film;ImageView preview;TextView status,info,hist;Uri current;Bitmap source;ArrayList<Uri> library=new ArrayList<>();int selected=0;int cyan=Color.rgb(0,183,217),violet=Color.rgb(142,108,245),bg=Color.rgb(8,10,16),panel=Color.rgb(17,19,23);int pending=0;HashMap<String,Integer> vals=new HashMap<>();
 String active="REVELAÇÃO";
 public void onCreate(Bundle b){super.onCreate(b);for(String k:new String[]{"exposure","contrast","sat","temp","tint","bright","sharp","red","green","blue","fade"})vals.put(k,50);build();}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(14,10,14,10);return v;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setTextColor(Color.WHITE);GradientDrawable g=new GradientDrawable();g.setColor(panel);g.setStroke(2,cyan);g.setCornerRadius(20);x.setBackground(g);return x;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(4,6,14),Color.rgb(20,8,38),Color.rgb(3,18,34)}));setContentView(root);
 TextView h=t("AURION T8i · QUANTUM PHOTO STUDIO",18);h.setTextColor(cyan);root.addView(h);status=t("v0.5 · QUANTUM EDITOR · OPPO",12);status.setTextColor(violet);root.addView(status);
 HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout nav=new LinearLayout(this);String[] ns={"BIBLIOTECA","LUZ","COR","MIX RGB","DETALHE","AUTO","CONVERSOR","ENTREGA","LAB"};
 for(String n:ns){Button x=b(n);x.setOnClickListener(v->open(((Button)v).getText().toString()));nav.addView(x);}hs.addView(nav);root.addView(hs);
 content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(10,8,10,8);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));
 preview=new ImageView(this);preview.setBackgroundColor(Color.BLACK);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);content.addView(preview,new LinearLayout.LayoutParams(-1,0,1));
 info=t("Importe JPG, PNG ou WebP para editar.",11);content.addView(info);hist=t("HISTOGRAMA: —",10);hist.setTextColor(Color.LTGRAY);content.addView(hist); film=new LinearLayout(this);film.setOrientation(LinearLayout.HORIZONTAL);HorizontalScrollView fs=new HorizontalScrollView(this);fs.setHorizontalScrollBarEnabled(false);fs.addView(film);content.addView(fs,new LinearLayout.LayoutParams(-1,110));
 tools=new LinearLayout(this);tools.setOrientation(LinearLayout.VERTICAL);content.addView(tools);open("REVELAÇÃO");}
 void open(String n){active=n;tools.removeAllViews();status.setText(n+" · funcional");
 if(n.equals("BIBLIOTECA")){Button x=b("IMPORTAR ARQUIVO");x.setOnClickListener(v->pick());tools.addView(x);}
 else if(n.equals("REVELAÇÃO")||n.equals("LUZ")){slider("Exposição","exposure");slider("Brilho","bright");slider("Contraste","contrast");Button r=b("RESET");r.setOnClickListener(v->reset());tools.addView(r);}
 else if(n.equals("COR")){slider("Temperatura","temp");slider("Matiz","tint");slider("Saturação","sat");slider("Desvanecer","fade");}\n else if(n.equals("MIX RGB")){slider("Vermelho","red");slider("Verde","green");slider("Azul","blue");}\n else if(n.equals("DETALHE")){slider("Nitidez","sharp");}
 else if(n.equals("AUTO")){Button x=b("ANALISAR E APLICAR AUTO");x.setOnClickListener(v->auto());tools.addView(x);}
 else if(n.equals("CONVERSOR")){Button j=b("CONVERTER → JPEG");j.setOnClickListener(v->save(0));tools.addView(j);Button p=b("CONVERTER → PNG");p.setOnClickListener(v->save(1));tools.addView(p);Button w=b("CONVERTER → WEBP");w.setOnClickListener(v->save(2));tools.addView(w);}
 else if(n.equals("ENTREGA")){Button x=b("EXPORTAR MASTER");x.setOnClickListener(v->chooseMaster());tools.addView(x);}
 else if(n.equals("LAB")){TextView q=t(source==null?"Sem imagem carregada.":"Imagem: "+source.getWidth()+"×"+source.getHeight()+"\nMemória bitmap: "+source.getByteCount()/1024+" KB\nEngine: Android Bitmap/Canvas\nProcessamento: local/offline",12);tools.addView(q);}
 }
 void slider(String label,String key){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);TextView l=t(label,11);r.addView(l,new LinearLayout.LayoutParams(0,-2,.3f));SeekBar s=new SeekBar(this);s.setMax(100);s.setProgress(vals.get(key));s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar z,int p,boolean f){vals.put(key,p);render();}public void onStartTrackingTouch(SeekBar z){}public void onStopTrackingTouch(SeekBar z){}});r.addView(s,new LinearLayout.LayoutParams(0,-2,.7f));tools.addView(r);}
 void reset(){for(String k:vals.keySet())vals.put(k,50);open(active);render();status.setText("Ajustes zerados");}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,10);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null)return;if(r==10){library.clear();if(d.getClipData()!=null){for(int i=0;i<d.getClipData().getItemCount();i++)library.add(d.getClipData().getItemAt(i).getUri());}else if(d.getData()!=null)library.add(d.getData());for(Uri u:library){try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception e){}}selected=0;if(!library.isEmpty()){current=library.get(0);load();refreshFilm();status.setText(library.size()+" arquivo(s) carregado(s) · toque nas miniaturas");}}else if(r==20)export(d.getData());}
 String name(Uri u){try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Exception e){}return "foto";}
 void refreshFilm(){film.removeAllViews();for(int i=0;i<library.size();i++){final int ix=i;ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setPadding(4,4,4,4);try(InputStream z=getContentResolver().openInputStream(library.get(i))){BitmapFactory.Options op=new BitmapFactory.Options();op.inSampleSize=16;Bitmap th=BitmapFactory.decodeStream(z,null,op);if(th!=null)im.setImageBitmap(th);}catch(Exception e){}GradientDrawable gd=new GradientDrawable();gd.setColor(Color.rgb(12,13,24));gd.setStroke(i==selected?5:2,i==selected?violet:cyan);gd.setCornerRadius(18);im.setBackground(gd);im.setOnClickListener(v->{selected=ix;current=library.get(ix);load();refreshFilm();});film.addView(im,new LinearLayout.LayoutParams(120,100));}}
 void load(){try(InputStream in=getContentResolver().openInputStream(current)){source=BitmapFactory.decodeStream(in);if(source==null){status.setText("Formato sem decoder nesta build");return;}info.setText(name(current)+" · "+source.getWidth()+"×"+source.getHeight());render();calcHist();status.setText("Imagem carregada · edição não destrutiva");}catch(Exception e){status.setText("Erro: "+e.getMessage());}}
 ColorMatrix matrix(){float ev=(vals.get("exposure")-50)/50f,br=(vals.get("bright")-50)*2f,co=(vals.get("contrast")-50)/50f+1f,sa=vals.get("sat")/50f,te=(vals.get("temp")-50)*1.5f,ti=(vals.get("tint")-50)*1.2f,sc=(float)Math.pow(2,ev),off=128*(1-co)+br,rg=vals.get("red")/50f,gg=vals.get("green")/50f,bg=vals.get("blue")/50f,fade=(vals.get("fade")-50)*0.7f;ColorMatrix m=new ColorMatrix(new float[]{sc*co*rg,0,0,0,off+te+ti+fade,0,sc*co*gg,0,0,off-ti+fade,0,0,sc*co*bg,0,off-te+ti+fade,0,0,0,1,0});ColorMatrix sm=new ColorMatrix();sm.setSaturation(sa);m.postConcat(sm);return m;}
 void render(){if(source==null)return;preview.setImageBitmap(source);preview.setColorFilter(new ColorMatrixColorFilter(matrix()));}
 Bitmap rendered(){if(source==null)return null;Bitmap o=Bitmap.createBitmap(source.getWidth(),source.getHeight(),Bitmap.Config.ARGB_8888);Canvas c=new Canvas(o);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);p.setColorFilter(new ColorMatrixColorFilter(matrix()));c.drawBitmap(source,0,0,p);int sh=vals.get("sharp")-50;if(sh>3){Paint edge=new Paint();edge.setAlpha(Math.min(80,sh));edge.setColorFilter(new ColorMatrixColorFilter(new ColorMatrix(new float[]{1.2f,0,0,0,-20,0,1.2f,0,0,-20,0,0,1.2f,0,-20,0,0,0,1,0})));c.drawBitmap(o,0,0,edge);}return o;}
 void calcHist(){if(source==null)return;int[] bins=new int[16];int sx=Math.max(1,source.getWidth()/160),sy=Math.max(1,source.getHeight()/160);long sum=0,n=0;for(int y=0;y<source.getHeight();y+=sy)for(int x=0;x<source.getWidth();x+=sx){int c=source.getPixel(x,y),v=(Color.red(c)+Color.green(c)+Color.blue(c))/3;bins[Math.min(15,v/16)]++;sum+=v;n++;}StringBuilder s=new StringBuilder("HIST ");int mx=1;for(int v:bins)mx=Math.max(mx,v);String chars="▁▂▃▄▅▆▇█";for(int v:bins)s.append(chars.charAt(Math.min(7,v*8/mx)));s.append("  Luma ").append(n==0?0:sum/n);hist.setText(s.toString());}
 void auto(){if(source==null){status.setText("Importe uma imagem primeiro");return;}int sx=Math.max(1,source.getWidth()/100),sy=Math.max(1,source.getHeight()/100);long sum=0,n=0;for(int y=0;y<source.getHeight();y+=sy)for(int x=0;x<source.getWidth();x+=sx){int c=source.getPixel(x,y);sum+=(Color.red(c)+Color.green(c)+Color.blue(c))/3;n++;}float mean=n==0?128:(float)sum/n;vals.put("exposure",Math.max(35,Math.min(65,50+Math.round((128-mean)/12))));vals.put("contrast",54);vals.put("sat",52);render();calcHist();status.setText("AUTO analisou luminância · ajustes conservadores aplicados");}
 void chooseMaster(){if(source==null){status.setText("Importe uma imagem primeiro");return;}final String[] a={"JPEG 100%","PNG lossless","WEBP lossless"};new AlertDialog.Builder(this).setTitle("ENTREGA MASTER").setItems(a,(d,w)->save(w)).show();}
 void save(int type){if(source==null){status.setText("Importe uma imagem primeiro");return;}pending=type;String mime=type==1?"image/png":type==2?"image/webp":"image/jpeg",ext=type==1?".png":type==2?".webp":".jpg";Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);i.putExtra(Intent.EXTRA_TITLE,"AURION_"+System.currentTimeMillis()+ext);startActivityForResult(i,20);}
 void export(Uri u){Bitmap o=rendered();try(OutputStream os=getContentResolver().openOutputStream(u)){Bitmap.CompressFormat f=pending==1?Bitmap.CompressFormat.PNG:pending==2?Bitmap.CompressFormat.WEBP_LOSSLESS:Bitmap.CompressFormat.JPEG;if(o.compress(f,100,os))status.setText("Arquivo convertido/exportado com sucesso");else status.setText("Falha no codec");}catch(Exception e){status.setText("Erro: "+e.getMessage());}finally{if(o!=null)o.recycle();}}
}