"""AURION ONE: integrated local agent UI; reuses existing authenticated API."""
from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()


@router.get('/one', response_class=HTMLResponse)
async def one_panel():
    return r'''<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AURION ONE | Central + Canon T8i</title>
<style>
:root{color-scheme:dark;font:16px system-ui;--bg:#050d18;--panel:#0d2037;--panel2:#112a46;--line:#285b86;--blue:#1b75d0;--cyan:#5ee7ff;--green:#74e8a8;--amber:#ffc16a;--red:#ff7d7d;--muted:#a9bfd5}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#04101d,#081a2e 55%,#050d18);color:#eef7ff;min-height:100vh}
header{position:sticky;top:0;z-index:5;padding:14px 20px;background:#07182beF;border-bottom:1px solid #24567f;backdrop-filter:blur(10px);display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}
h1{font-size:1.2rem;margin:0}.brand{color:var(--cyan)}small,.muted{color:var(--muted)}#auth{display:flex;gap:8px;min-width:min(100%,430px)}
button,input,textarea,select{font:inherit;border-radius:9px;padding:10px;border:1px solid #3b78a9;color:white;background:#07192d}button{background:#155c9e;cursor:pointer}button:hover{filter:brightness(1.12)}button:disabled{opacity:.5;cursor:wait}.secondary{background:#102a43}.danger{background:#73353a}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}
.tabs{max-width:1240px;margin:14px auto 0;padding:0 16px;display:flex;gap:8px;flex-wrap:wrap}.tabbtn.active{background:#1b75d0;border-color:#70c6ff}.tab{display:none}.tab.active{display:block}
main{max-width:1240px;margin:auto;padding:16px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px}.card{border:1px solid var(--line);border-radius:14px;background:linear-gradient(180deg,#102743,#0b1c31);padding:16px;min-width:0}.wide{grid-column:1/-1}.status{display:flex;justify-content:space-between;gap:8px;padding:9px 0;border-bottom:1px solid #243f5a}.on{color:var(--green)}.off{color:var(--amber)}.unknown{color:#c2cbd8}
#messages,#t8iMessages{height:320px;overflow:auto;display:flex;flex-direction:column;gap:9px;padding:8px 0;white-space:pre-wrap;overflow-wrap:anywhere}.bubble{padding:11px;border-radius:11px;background:#183a5c;max-width:94%;align-self:flex-start}.mine{background:#18558b;align-self:flex-end}.error{border:1px solid #d08a58}.toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.toolbar>*{width:auto}.pathrow{display:grid;grid-template-columns:1fr auto auto;gap:8px}.twocol{display:grid;grid-template-columns:1fr 1fr;gap:10px}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.control label{display:block;font-size:.84rem;color:var(--muted);margin-bottom:4px}.control input[type=range]{width:100%;padding:0}.control output{font-variant-numeric:tabular-nums;color:var(--cyan)}
#t8iFileList{max-height:280px;overflow:auto;border:1px solid #254a6b;border-radius:10px}.fileitem{display:flex;justify-content:space-between;gap:8px;align-items:center;padding:9px 10px;border-bottom:1px solid #243f5a}.fileitem:last-child{border-bottom:none}.fileitem button{padding:6px 9px}.selected{background:#153b5f}.previewbox{min-height:420px;display:grid;place-items:center;border:1px dashed #3a6f95;border-radius:12px;background:#06111e;overflow:hidden}.previewbox img{max-width:100%;max-height:68vh;object-fit:contain}.badge{display:inline-block;border:1px solid #3f6f91;border-radius:999px;padding:4px 8px;font-size:.8rem;margin:2px}.deps{display:flex;gap:6px;flex-wrap:wrap}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:280px;overflow:auto}.note{border-left:3px solid var(--amber);padding-left:10px;color:#d6e5f3}.success{border-left-color:var(--green)}
@media(max-width:900px){.grid,.grid3{grid-template-columns:1fr}.wide{grid-column:auto}.controls{grid-template-columns:1fr 1fr}.pathrow{grid-template-columns:1fr}.pathrow>*{width:100%}}@media(max-width:560px){.controls,.twocol{grid-template-columns:1fr}header{align-items:stretch}#auth{width:100%}#auth input{min-width:0;flex:1}}
</style></head>
<body><header><div><h1>AURION<span class="brand">#ONE</span> · Central local</h1><small>Agente + laboratório Canon T8i com salvamento auditável</small></div><div id="auth"><input id="token" type="password" autocomplete="off" placeholder="Token local AURION"><button id="connect">Conectar</button></div></header>
<div class="tabs"><button class="tabbtn active" data-tab="central">Central</button><button class="tabbtn" data-tab="t8i">Canon T8i · CR3</button></div>
<main>
<section id="tab-central" class="tab active"><div class="grid">
<section class="card"><h2>Conexões verificadas</h2><div class="status">Portal <strong id="portal" class="unknown">verificando</strong></div><div class="status">Ollama <strong id="ollama" class="unknown">aguardando autenticação</strong></div><div class="status">ComfyUI <strong id="comfy" class="unknown">não verificado</strong></div><div class="status">POCO <strong id="poco" class="unknown">não verificado</strong></div><p class="muted" id="notice">O token fica apenas nesta sessão. Não envie a chave no chat.</p><button id="refresh">Atualizar estado</button></section>
<section class="card"><h2>Chat integrado · AURION</h2><div id="messages" role="log"><div class="bubble">Conecte o token para conversar com o agente local.</div></div><form id="chat"><textarea id="message" rows="3" maxlength="12000" placeholder="Escreva para o agente..." required></textarea><button id="send" type="submit">Enviar</button></form><small>Resposta do agente não significa execução de uma tarefa no PC.</small></section>
<section class="card wide"><h2>Diagnóstico e inventário</h2><button id="inventoryButton">Ler inventário salvo</button><pre id="inventory">Nenhum scan novo será iniciado automaticamente.</pre></section>
</div></section>

<section id="tab-t8i" class="tab"><div class="grid">
<section class="card wide"><div class="toolbar" style="justify-content:space-between"><div><h2 style="margin:0">Canon EOS Rebel T8i · laboratório RAW</h2><small>CR3 estático: revelação não destrutiva. O original nunca é sobrescrito.</small></div><button id="t8iRefresh" class="secondary">Atualizar diagnóstico</button></div><div id="t8iDeps" class="deps" style="margin-top:12px"></div><p id="t8iStatus" class="note">Conecte o token para carregar a aba.</p></section>

<section class="card wide"><h2>1 · Pasta de trabalho</h2><p class="muted">Você escolhe onde guardar tudo. A estrutura criada é: RAW / PREVIEWS / EXPORTS / CONVERSAS / PRESETS / LOGS.</p><div class="pathrow"><input id="workspacePath" placeholder="Ex.: D:\\FOTOS\\AURION_T8I"><button id="pickWorkspace">Escolher pasta</button><button id="saveWorkspace">Criar / usar estrutura</button></div><small id="workspaceInfo">Nenhuma pasta escolhida.</small></section>

<section class="card"><h2>2 · Importar CR3</h2><div class="toolbar"><button id="pickRaw">Escolher CR3</button><button id="importRaw" disabled>Copiar para RAW</button><button id="reloadFiles" class="secondary">Atualizar lista</button></div><pre id="pickedRaw">Nenhum arquivo selecionado.</pre><p class="note">Os arquivos externos são copiados; o original da câmera/cartão não é movido.</p></section>
<section class="card"><h2>Arquivos do projeto</h2><div id="t8iFileList"><div class="fileitem muted">Nenhum CR3 carregado.</div></div></section>

<section class="card wide"><h2>3 · Revelação</h2><div class="controls">
<div class="control"><label>Exposição EV <output id="exposureOut">0.0</output></label><input id="exposure" type="range" min="-4" max="4" step="0.1" value="0"></div>
<div class="control"><label>Brilho <output id="brightnessOut">1.00</output></label><input id="brightness" type="range" min="0.1" max="3" step="0.05" value="1"></div>
<div class="control"><label>Contraste <output id="contrastOut">1.00</output></label><input id="contrast" type="range" min="0.1" max="3" step="0.05" value="1"></div>
<div class="control"><label>Saturação <output id="saturationOut">1.00</output></label><input id="saturation" type="range" min="0" max="3" step="0.05" value="1"></div>
<div class="control"><label>Gamma <output id="gammaOut">2.20</output></label><input id="gamma" type="range" min="1" max="3" step="0.05" value="2.2"></div>
<div class="control"><label>Balanço de branco</label><select id="wb"><option value="camera">Da câmera</option><option value="auto">Automático</option><option value="neutral">Neutro LibRaw</option></select></div>
</div><div class="toolbar" style="margin-top:12px"><button id="makePreview">Gerar preview</button><select id="exportFormat"><option value="jpeg">JPEG alta qualidade</option><option value="tiff16">TIFF 16-bit</option><option value="png">PNG</option></select><button id="exportFile">Exportar</button><span id="selectedName" class="muted">Nenhum CR3 selecionado.</span></div></section>

<section class="card wide"><div class="previewbox"><img id="previewImage" alt="Preview revelado" style="display:none"><span id="previewEmpty" class="muted">O preview aparecerá aqui.</span></div><p id="previewInfo" class="muted"></p></section>

<section class="card"><h2>4 · Depósito de conversas</h2><div class="twocol"><input id="convName" placeholder="Nome da sessão, ex.: Ensaio Wilson"><button id="newConversation">Nova conversa</button></div><div class="status">Sessão atual <strong id="convId" class="unknown">nenhuma</strong></div><div class="toolbar"><button id="reloadConversations" class="secondary">Listar salvas</button></div><pre id="convList">Nenhuma sessão listada.</pre></section>
<section class="card"><h2>Chat / notas da T8i</h2><div id="t8iMessages"><div class="bubble">Tudo enviado aqui pode ser salvo em CONVERSAS como JSONL, com gravação imediata.</div></div><textarea id="t8iMessage" rows="3" maxlength="12000" placeholder="Anotação ou pergunta sobre a foto..."></textarea><div class="toolbar"><button id="saveNote">Salvar nota</button><button id="askT8i">Perguntar ao agente + salvar</button></div><small>O histórico desta aba é separado do chat geral e fica dentro da pasta escolhida.</small></section>
</div></section>
</main>
<script>
'use strict';
const $=id=>document.getElementById(id);let key=sessionStorage.getItem('aurion_one_session_token')||localStorage.getItem('aurion_token')||'';let pickedPaths=[];let selectedFile='';let previewUrl='';let convSession='';$('token').value=key;
const set=(id,value,cls)=>{const e=$(id);e.textContent=value;e.className=cls};const note=s=>$('notice').textContent=s;
async function api(path,opts={}){if(!key)throw Error('Informe o token local.');const r=await fetch(path,{...opts,headers:{...(opts.headers||{}),Authorization:'Bearer '+key}});let data;try{data=await r.json()}catch{throw Error('Resposta inválida do servidor ('+r.status+')')}if(!r.ok)throw Error(data.detail||'HTTP '+r.status);return data}
async function apiBlob(path){if(!key)throw Error('Informe o token local.');const r=await fetch(path,{headers:{Authorization:'Bearer '+key}});if(!r.ok){let msg='HTTP '+r.status;try{const j=await r.json();msg=j.detail||msg}catch{}throw Error(msg)}return await r.blob()}
function jsonPost(path,body){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
function bubble(container,text,mine=false,error=false){const d=document.createElement('div');d.className='bubble'+(mine?' mine':'')+(error?' error':'');d.textContent=text;$(container).append(d);$(container).scrollTop=$(container).scrollHeight;return d}
function switchTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabbtn').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$('tab-'+name).classList.add('active');if(name==='t8i'&&key)t8iStatus()}
document.querySelectorAll('.tabbtn').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
async function status(){try{const r=await fetch('/health',{cache:'no-store'});set('portal',r.ok?'online':'erro',r.ok?'on':'off')}catch{set('portal','offline','off')}if(!key){set('ollama','sem token','unknown');return}try{const s=await api('/api/status');set('ollama',s.ollama==='online'?'online':'offline',s.ollama==='online'?'on':'off');const devices=Array.isArray(s.devices)?s.devices:[];set('poco',devices.some(d=>/poco/i.test(String(d.device_id||'')))?'registrado (não garante conexão atual)':'não verificado','unknown');note('Estado consultado no servidor.')}catch(e){set('ollama','não verificado','unknown');note('Falha: '+e.message)}}
$('connect').onclick=async()=>{key=$('token').value.trim();if(!key){note('Informe a chave local.');return}try{await api('/api/status');sessionStorage.setItem('aurion_one_session_token',key);localStorage.setItem('aurion_token',key);note('Token validado.');await status();if($('tab-t8i').classList.contains('active'))await t8iStatus()}catch(e){note('Não conectado: '+e.message)}};
$('refresh').onclick=status;$('inventoryButton').onclick=async()=>{try{$('inventory').textContent=JSON.stringify(await api('/api/inventory'),null,2)}catch(e){$('inventory').textContent='Falha: '+e.message}};
$('chat').onsubmit=async e=>{e.preventDefault();const text=$('message').value.trim();if(!text)return;bubble('messages',text,true);$('message').value='';$('send').disabled=true;const waiting=bubble('messages','Aguardando resposta...');try{const r=await jsonPost('/api/prompt',{text,device_id:'portal-pc',moving:false});waiting.textContent=r.answer||('Estado: '+r.status);if(r.status!=='completed')waiting.classList.add('error')}catch(err){waiting.textContent='Erro real: '+err.message;waiting.classList.add('error')}finally{$('send').disabled=false}};

async function t8iStatus(){try{const s=await api('/api/t8i/status');$('workspacePath').value=s.workspace||'';$('workspaceInfo').textContent=s.workspace?'Ativo: '+s.workspace:'Nenhuma pasta escolhida.';const dep=$('t8iDeps');dep.textContent='';Object.entries(s.dependencies||{}).forEach(([name,v])=>{const b=document.createElement('span');b.className='badge '+(v.ok?'ok':'bad');b.textContent=name+': '+(v.ok?(v.version||'OK'):'faltando');dep.appendChild(b)});$('t8iStatus').textContent=s.workspace?'Aba pronta. Originais protegidos.':'Escolha a pasta de trabalho para começar.';$('t8iStatus').className='note '+(s.workspace?'success':'');if(s.workspace){await loadFiles();await listConversations()}}catch(e){$('t8iStatus').textContent='Falha no diagnóstico: '+e.message;$('t8iStatus').className='note'}}
$('t8iRefresh').onclick=t8iStatus;
$('pickWorkspace').onclick=async()=>{try{const r=await api('/api/t8i/workspace/pick',{method:'POST'});if(r.cancelled)return;$('workspacePath').value=r.workspace;$('workspaceInfo').textContent='Ativo: '+r.workspace;await t8iStatus()}catch(e){$('workspaceInfo').textContent='Falha: '+e.message}};
$('saveWorkspace').onclick=async()=>{const path=$('workspacePath').value.trim();if(!path)return;try{const r=await jsonPost('/api/t8i/workspace',{path});$('workspaceInfo').textContent='Estrutura criada: '+r.workspace;await t8iStatus()}catch(e){$('workspaceInfo').textContent='Falha: '+e.message}};
$('pickRaw').onclick=async()=>{try{const r=await api('/api/t8i/files/pick',{method:'POST'});pickedPaths=r.paths||[];$('pickedRaw').textContent=pickedPaths.length?pickedPaths.join('\n'):'Seleção cancelada.';$('importRaw').disabled=!pickedPaths.length}catch(e){$('pickedRaw').textContent='Falha: '+e.message}};
$('importRaw').onclick=async()=>{if(!pickedPaths.length)return;$('importRaw').disabled=true;try{const r=await jsonPost('/api/t8i/import',{paths:pickedPaths,copy:true});$('pickedRaw').textContent='Importados: '+r.imported.length+'\nRejeitados: '+r.rejected.length+(r.rejected.length?'\n'+JSON.stringify(r.rejected,null,2):'');pickedPaths=[];await loadFiles()}catch(e){$('pickedRaw').textContent='Falha: '+e.message}finally{$('importRaw').disabled=false}};
$('reloadFiles').onclick=loadFiles;
async function loadFiles(){try{const r=await api('/api/t8i/files');const box=$('t8iFileList');box.textContent='';if(!r.files.length){box.innerHTML='<div class="fileitem muted">Nenhum CR3 carregado.</div>';return}r.files.forEach(f=>{const row=document.createElement('div');row.className='fileitem'+(f.name===selectedFile?' selected':'');const label=document.createElement('span');label.textContent=f.name+' · '+(f.size/1048576).toFixed(1)+' MB';const btn=document.createElement('button');btn.textContent='Selecionar';btn.onclick=()=>{selectedFile=f.name;$('selectedName').textContent='Selecionado: '+f.name;loadFiles()};row.append(label,btn);box.appendChild(row)})}catch(e){$('t8iFileList').textContent='Falha: '+e.message}}
[['exposure','exposureOut',1],['brightness','brightnessOut',2],['contrast','contrastOut',2],['saturation','saturationOut',2],['gamma','gammaOut',2]].forEach(([id,out,d])=>{$(id).oninput=()=>$(out).textContent=Number($(id).value).toFixed(d)});
function developPayload(){if(!selectedFile)throw Error('Selecione um CR3 primeiro.');const wb=$('wb').value;return{file:selectedFile,exposure_ev:Number($('exposure').value),brightness:Number($('brightness').value),contrast:Number($('contrast').value),saturation:Number($('saturation').value),gamma:Number($('gamma').value),use_camera_wb:wb==='camera',auto_wb:wb==='auto'}}
$('makePreview').onclick=async()=>{try{$('previewInfo').textContent='Revelando CR3...';const r=await jsonPost('/api/t8i/preview',developPayload());const blob=await apiBlob('/api/t8i/media/PREVIEWS/'+encodeURIComponent(r.preview));if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);$('previewImage').src=previewUrl;$('previewImage').style.display='block';$('previewEmpty').style.display='none';$('previewInfo').textContent='Preview: '+r.preview+' · '+r.created_at}catch(e){$('previewInfo').textContent='Falha: '+e.message}};
$('exportFile').onclick=async()=>{try{const p=developPayload();p.format=$('exportFormat').value;p.quality=94;const r=await jsonPost('/api/t8i/export',p);$('previewInfo').textContent='Exportado sem sobrescrever o RAW: '+r.path}catch(e){$('previewInfo').textContent='Falha: '+e.message}};
async function ensureConversation(){if(convSession)return convSession;const r=await jsonPost('/api/t8i/conversations/start',{name:$('convName').value.trim()||('T8i '+new Date().toLocaleString())});convSession=r.session_id;$('convId').textContent=convSession;$('convId').className='ok';await listConversations();return convSession}
$('newConversation').onclick=async()=>{convSession='';try{await ensureConversation();bubble('t8iMessages','Nova conversa iniciada: '+convSession,false)}catch(e){bubble('t8iMessages','Falha: '+e.message,false,true)}};
async function appendConversation(role,content,attachments=[]){const id=await ensureConversation();return jsonPost('/api/t8i/conversations/append',{session_id:id,role,content,attachments})}
$('saveNote').onclick=async()=>{const text=$('t8iMessage').value.trim();if(!text)return;try{await appendConversation('note',text,selectedFile?[selectedFile]:[]);bubble('t8iMessages',text,true);$('t8iMessage').value=''}catch(e){bubble('t8iMessages','Falha ao salvar: '+e.message,false,true)}};
$('askT8i').onclick=async()=>{const text=$('t8iMessage').value.trim();if(!text)return;$('askT8i').disabled=true;try{await appendConversation('user',text,selectedFile?[selectedFile]:[]);bubble('t8iMessages',text,true);$('t8iMessage').value='';const q=selectedFile?'Contexto da aba Canon T8i, arquivo selecionado '+selectedFile+'. '+text:text;const r=await jsonPost('/api/prompt',{text:q,device_id:'portal-t8i',moving:false});const answer=r.answer||('Estado: '+r.status);bubble('t8iMessages',answer,false,r.status!=='completed');await appendConversation('assistant',answer,selectedFile?[selectedFile]:[])}catch(e){bubble('t8iMessages','Falha: '+e.message,false,true)}finally{$('askT8i').disabled=false}};
$('reloadConversations').onclick=listConversations;async function listConversations(){try{const r=await api('/api/t8i/conversations');$('convList').textContent=r.conversations.length?r.conversations.map(x=>x.created_at+'  '+x.name+'\n'+x.session_id).join('\n\n'):'Nenhuma conversa salva.'}catch(e){$('convList').textContent='Falha: '+e.message}}
const fragment=new URLSearchParams(location.hash.slice(1));const incoming=fragment.get('token');if(incoming){key=incoming;sessionStorage.setItem('aurion_one_session_token',key);localStorage.setItem('aurion_token',key);$('token').value=key;history.replaceState(null,'',location.pathname)}status();
</script></body></html>'''
