"""AURION ONE: integrated local agent UI; reuses existing authenticated API."""
from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter()

@router.get('/one', response_class=HTMLResponse)
async def one_panel():
    return r'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AURION ONE | Agente</title><style>
:root{color-scheme:dark;font:16px system-ui}*{box-sizing:border-box}body{margin:0;background:#061326;color:#edf6ff}header{padding:18px 22px;background:#0b2444;border-bottom:1px solid #2767a0;display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}h1{font-size:1.25rem;margin:0}h2{font-size:1.05rem}small,.muted{color:#b1c5dc}main{max-width:1100px;margin:auto;padding:16px;display:grid;grid-template-columns:1fr 1.5fr;gap:14px}.card{border:1px solid #275783;border-radius:14px;background:#102744;padding:16px;min-width:0}.wide{grid-column:1/-1}button,input,textarea{font:inherit;border-radius:9px;padding:11px;border:1px solid #4380b6;color:white;background:#0a1c33}button{background:#185eaa;cursor:pointer}button:disabled{opacity:.5;cursor:wait}input,textarea{width:100%}textarea{resize:vertical}.status{display:flex;justify-content:space-between;gap:8px;padding:9px 0;border-bottom:1px solid #274464}.on{color:#77e4aa}.off{color:#ffc18b}.unknown{color:#c2cbd8}#messages{height:360px;overflow:auto;display:flex;flex-direction:column;gap:10px;padding:8px 0;white-space:pre-wrap;overflow-wrap:anywhere}.bubble{padding:12px;border-radius:12px;background:#1a395a;max-width:94%;align-self:flex-start}.mine{background:#184e86;align-self:flex-end}.error{border:1px solid #d08a58}form{display:flex;gap:8px;align-items:end}form textarea{flex:1}form button{width:auto}#auth{display:flex;gap:8px}#auth input{max-width:320px}#auth button{white-space:nowrap}a{color:#8bc6ff}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:250px;overflow:auto} @media(max-width:720px){main{grid-template-columns:1fr}.wide{grid-column:auto}header{align-items:stretch}#auth{width:100%}#auth input{min-width:0;flex:1}form{align-items:stretch;flex-direction:column}}
</style></head><body><header><div><h1>AURION ONE · agente local</h1><small>Respostas reais do Ollama; sem simular conexões</small></div><div id="auth"><input id="token" type="password" autocomplete="off" placeholder="Token local AURION" aria-label="Token local"><button id="connect">Conectar</button></div></header><main><section class="card"><h2>Conexões verificadas</h2><div class="status">Portal <strong id="portal" class="unknown">verificando</strong></div><div class="status">Ollama <strong id="ollama" class="unknown">aguardando autenticação</strong></div><div class="status">ComfyUI <strong id="comfy" class="unknown">não verificado</strong></div><div class="status">POCO <strong id="poco" class="unknown">não verificado</strong></div><div class="status">Drive / ChatGPT / Gemini <strong class="unknown">não conectados neste painel</strong></div><p class="muted" id="notice">O token fica apenas nesta sessão do navegador. Use a chave do arquivo .env local; não a envie no chat.</p><button id="refresh">Atualizar estado</button></section><section class="card"><h2>Chat integrado · AURION</h2><div id="messages" role="log" aria-live="polite"><div class="bubble">Conecte o token para conversar com o agente local. Nenhum comando do PC é executado pelo chat.</div></div><form id="chat"><textarea id="message" rows="3" maxlength="12000" placeholder="Escreva para o agente..." required></textarea><button id="send" type="submit">Enviar</button></form><small>O agente usa o endpoint /api/prompt e o modelo configurado no servidor. Uma resposta não significa que uma tarefa foi executada.</small></section><section class="card wide"><h2>Diagnóstico e inventário</h2><button id="inventoryButton">Ler inventário salvo</button><pre id="inventory">Nenhum scan novo será iniciado automaticamente.</pre><p class="muted">Imagem, vídeo e reparo automático ainda não estão implementados neste painel. Não serão mostrados como ativos.</p></section></main><script>
'use strict';const $=id=>document.getElementById(id);let key=sessionStorage.getItem('aurion_one_session_token')||localStorage.getItem('aurion_token')||'';$('token').value=key;const set=(id,value,cls)=>{const e=$(id);e.textContent=value;e.className=cls};const note=s=>$('notice').textContent=s;async function api(path,opts={}){if(!key)throw Error('Informe o token local.');const r=await fetch(path,{...opts,headers:{...(opts.headers||{}),Authorization:'Bearer '+key}});let data;try{data=await r.json()}catch{throw Error('Resposta inválida do servidor ('+r.status+')')}if(!r.ok)throw Error(data.detail||'HTTP '+r.status);return data}async function status(){try{const r=await fetch('/health',{cache:'no-store'});set('portal',r.ok?'online':'erro',r.ok?'on':'off')}catch{set('portal','offline','off')}if(!key){set('ollama','sem token','unknown');return}try{const s=await api('/api/status');set('ollama',s.ollama==='online'?'online':'offline',s.ollama==='online'?'on':'off');const devices=Array.isArray(s.devices)?s.devices:[];set('poco',devices.some(d=>/poco/i.test(String(d.device_id||'')))?'registrado (não garante conexão atual)':'não verificado','unknown');note('Estado consultado no servidor. ComfyUI não possui verificação nesta API.')}catch(e){set('ollama','não verificado','unknown');note('Falha na autenticação/estado: '+e.message)}}function bubble(text,mine=false,error=false){const d=document.createElement('div');d.className='bubble'+(mine?' mine':'')+(error?' error':'');d.textContent=text;$('messages').append(d);$('messages').scrollTop=$('messages').scrollHeight;return d}$('connect').onclick=async()=>{key=$('token').value.trim();if(!key){note('Informe a chave local.');return}try{await api('/api/status');sessionStorage.setItem('aurion_one_session_token',key);note('Token validado para esta sessão.');await status()}catch(e){note('Não conectado: '+e.message)}};$('refresh').onclick=status;$('inventoryButton').onclick=async()=>{try{$('inventory').textContent=JSON.stringify(await api('/api/inventory'),null,2)}catch(e){$('inventory').textContent='Falha: '+e.message}};$('chat').onsubmit=async e=>{e.preventDefault();const text=$('message').value.trim();if(!text)return;if(!key){note('Conecte o token primeiro.');return}bubble(text,true);$('message').value='';$('send').disabled=true;const waiting=bubble('Aguardando resposta do agente...');try{const r=await api('/api/prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,device_id:'portal-pc',moving:false})});waiting.textContent=r.answer||('Estado: '+r.status);if(r.status!=='completed')waiting.classList.add('error')}catch(err){waiting.textContent='Erro real: '+err.message;waiting.classList.add('error')}finally{$('send').disabled=false}};status();
</script></body></html>'''
