package one.aurion.mobileai;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.speech.tts.TextToSpeech;
import android.view.*;
import android.widget.*;
import androidx.security.crypto.EncryptedSharedPreferences;
import androidx.security.crypto.MasterKey;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener {
  static final int MIC=70; final int BG=Color.rgb(7,17,31), CARD=Color.rgb(17,35,58), FG=Color.WHITE;
  LinearLayout root, body; EditText input; TextView output, status; SharedPreferences secrets; TextToSpeech tts; SpeechRecognizer sr;
  @Override public void onCreate(Bundle b){super.onCreate(b); secrets=secure(); tts=new TextToSpeech(this,this); home();}
  SharedPreferences secure(){try{MasterKey k=new MasterKey.Builder(this).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();return EncryptedSharedPreferences.create(this,"vault",k,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM);}catch(Exception e){return getSharedPreferences("vault_fallback",MODE_PRIVATE);}}
  TextView tv(String s,int n){TextView v=new TextView(this);v.setText(s);v.setTextColor(FG);v.setTextSize(n);v.setPadding(18,15,18,15);return v;}
  Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
  EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(FG);e.setHintTextColor(Color.LTGRAY);e.setBackgroundColor(CARD);e.setPadding(18,16,18,16);return e;}
  void home(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.addView(tv("AURION MOBILE AI",24));status=tv(diag(),12);root.addView(status);LinearLayout nav=new LinearLayout(this);String[] ns={"Chat","Criar","Modelos","Contas"};for(String n:ns){Button b=btn(n);b.setOnClickListener(v->screen(n));nav.addView(b,new LinearLayout.LayoutParams(0,-2,1));}root.addView(nav);ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(16,12,16,30);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);screen("Chat");}
  void clear(String title){body.removeAllViews();body.addView(tv(title,21));}
  void screen(String s){if(s.equals("Chat"))chat();else if(s.equals("Criar"))create();else if(s.equals("Modelos"))models();else accounts();}
  void chat(){clear("Chat inteligente + voz");output=tv("Configure endpoint, chave e modelo em Contas. O microfone do fone Bluetooth é usado pelo Android quando estiver selecionado como entrada.",16);body.addView(output);input=field("Fale ou escreva sua mensagem");body.addView(input);LinearLayout r=new LinearLayout(this);Button mic=btn("🎙 Voz");mic.setOnClickListener(v->listen());Button send=btn("Enviar");send.setOnClickListener(v->chatRequest());r.addView(mic,new LinearLayout.LayoutParams(0,-2,1));r.addView(send,new LinearLayout.LayoutParams(0,-2,1));body.addView(r);}
  void chatRequest(){String endpoint=secrets.getString("chat_url","https://router.huggingface.co/v1/chat/completions"),key=secrets.getString("hf_key",""),model=secrets.getString("chat_model","Qwen/Qwen2.5-7B-Instruct");if(key.isEmpty()){toast("Cadastre a chave em Contas");return;}String q=input.getText().toString().trim();if(q.isEmpty())return;output.setText("Pensando...");try{JSONObject j=new JSONObject();j.put("model",model);JSONArray a=new JSONArray();a.put(new JSONObject().put("role","system").put("content","Você é AURION, assistente objetivo em português."));a.put(new JSONObject().put("role","user").put("content",q));j.put("messages",a);post(endpoint,key,j,res->{try{String x=new JSONObject(res).getJSONArray("choices").getJSONObject(0).getJSONObject("message").getString("content");ui(()->{output.setText(x);speak(x);});}catch(Exception e){ui(()->output.setText("Resposta não reconhecida:\n"+res));}});}catch(Exception e){output.setText(e.toString());}}
  void create(){clear("Imagem e vídeo");TextView info=tv("Usa endpoints de nuvem configurados. Qwen-Image, Wan e MiniMax completos não rodam localmente de forma prática no POCO X7.",15);body.addView(info);EditText p=field("Descreva a imagem ou vídeo");body.addView(p);Button im=btn("Gerar imagem");im.setOnClickListener(v->generation("image",p.getText().toString()));body.addView(im);Button vi=btn("Gerar vídeo");vi.setOnClickListener(v->generation("video",p.getText().toString()));body.addView(vi);output=tv("O resultado bruto/URL aparecerá aqui.",14);body.addView(output);}
  void generation(String kind,String prompt){String url=secrets.getString(kind+"_url",""),key=secrets.getString(kind+"_key",secrets.getString("hf_key","")),model=secrets.getString(kind+"_model","");if(url.isEmpty()||key.isEmpty()){toast("Configure endpoint e chave em Contas");return;}output.setText("Enviando...");try{JSONObject j=new JSONObject().put("model",model).put("prompt",prompt).put("inputs",prompt);post(url,key,j,res->ui(()->output.setText(res)));}catch(Exception e){output.setText(e.toString());}}
  void models(){clear("Modelos e arquivos");body.addView(tv("Baixe somente GGUF compatível e arquivos de fontes confiáveis. O gerenciador usa o DownloadManager do Android, mostra a notificação e permite retomar pelo sistema.",15));EditText url=field("URL HTTPS do Hugging Face ou GitHub");body.addView(url);EditText name=field("Nome do arquivo, ex.: modelo.gguf");body.addView(name);Button d=btn("Baixar arquivo");d.setOnClickListener(v->download(url.getText().toString(),name.getText().toString()));body.addView(d);Button hf=btn("Abrir Hugging Face");hf.setOnClickListener(v->open("https://huggingface.co/models?library=gguf"));body.addView(hf);Button gh=btn("Abrir GitHub");gh.setOnClickListener(v->open("https://github.com"));body.addView(gh);body.addView(tv("Importante: esta versão gerencia os modelos. O motor local GGUF ainda não está embutido; chat funciona pelo endpoint configurado.",14));}
  void accounts(){clear("Contas e provedores");body.addView(tv("As chaves ficam criptografadas no cofre do Android. Assinatura de site não é automaticamente uma chave de API.",14));addSecret("hf_key","Chave Hugging Face");addSecret("chat_url","Endpoint chat OpenAI-compatível");addSecret("chat_model","Modelo de chat");addSecret("image_url","Endpoint de imagem");addSecret("image_key","Chave de imagem (vazio usa HF)");addSecret("image_model","Modelo de imagem");addSecret("video_url","Endpoint de vídeo");addSecret("video_key","Chave de vídeo");addSecret("video_model","Modelo de vídeo");Button test=btn("Testar chat agora");test.setOnClickListener(v->{toast("Salvo. Abra Chat e envie uma mensagem.");screen("Chat");});body.addView(test);}
  void addSecret(String key,String label){EditText e=field(label);e.setText(secrets.getString(key,""));if(key.contains("key"))e.setInputType(129);e.setOnFocusChangeListener((v,has)->{if(!has)secrets.edit().putString(key,e.getText().toString().trim()).apply();});body.addView(e);}
  void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("Reconhecimento de voz indisponível");return;}sr=SpeechRecognizer.createSpeechRecognizer(this);sr.setRecognitionListener(new android.speech.RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float f){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){toast("Voz: erro "+e);}public void onResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty()){input.setText(x.get(0));chatRequest();}}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"pt-BR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);sr.startListening(i);toast("Ouvindo...");}
  void post(String endpoint,String key,JSONObject payload,java.util.function.Consumer<String> done){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(20000);c.setReadTimeout(120000);c.setRequestMethod("POST");c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(payload.toString().getBytes(StandardCharsets.UTF_8));}InputStream in=(c.getResponseCode()<400?c.getInputStream():c.getErrorStream());String res=read(in);done.accept(res);}catch(Exception e){ui(()->{if(output!=null)output.setText("Falha: "+e.getMessage());});}}).start();}
  String read(InputStream i)throws Exception{BufferedReader b=new BufferedReader(new InputStreamReader(i,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l).append('\n');return s.toString();}
  void download(String u,String n){try{Uri x=Uri.parse(u);if(!"https".equals(x.getScheme()))throw new Exception("Use HTTPS");if(n.trim().isEmpty())n=x.getLastPathSegment();DownloadManager.Request r=new DownloadManager.Request(x).setTitle(n).setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED).setDestinationInExternalFilesDir(this,android.os.Environment.DIRECTORY_DOWNLOADS,n);((DownloadManager)getSystemService(DOWNLOAD_SERVICE)).enqueue(r);toast("Download iniciado");}catch(Exception e){toast("URL inválida: "+e.getMessage());}}
  String diag(){return Build.MANUFACTURER+" "+Build.MODEL+" • Android "+Build.VERSION.RELEASE+" • "+(Runtime.getRuntime().maxMemory()/1048576)+" MB por processo";}
  void open(String u){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}void ui(Runnable r){runOnUiThread(r);}void toast(String s){ui(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}void speak(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"aurion");}
  public void onInit(int x){if(x==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("pt","BR"));}
  @Override protected void onDestroy(){if(sr!=null)sr.destroy();if(tts!=null)tts.shutdown();super.onDestroy();}
}
