package one.aurion.mobileai;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.ColorMatrix;
import android.graphics.ColorMatrixColorFilter;
import android.graphics.Paint;
import android.graphics.drawable.GradientDrawable;
import android.media.session.MediaSession;
import android.view.KeyEvent;
import android.net.Uri;
import android.os.*;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.speech.tts.TextToSpeech;
import android.view.*;
import android.widget.*;
import android.provider.MediaStore;
import android.content.ContentValues;
import android.text.method.LinkMovementMethod;
import androidx.security.crypto.EncryptedSharedPreferences;
import androidx.security.crypto.MasterKey;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener {
  static final int MIC=70, PICK_IMAGE=71, PICK_MEDIA=72, PICK_DRIVE=73; final int BG=Color.rgb(5,5,6), CARD=Color.rgb(24,21,18), FG=Color.rgb(245,244,240), ORANGE=Color.rgb(255,122,24);
  LinearLayout root, body; EditText input; TextView output, status; SharedPreferences secrets; TextToSpeech tts; SpeechRecognizer sr; Bitmap workingBitmap; ImageView preview; int mediaCount=0; MediaSession mediaSession; float voiceRate=1f,voicePitch=1f;
  @Override public void onCreate(Bundle b){super.onCreate(b); secrets=secure(); tts=new TextToSpeech(this,this);setupMediaButtons();home();}
  SharedPreferences secure(){try{MasterKey k=new MasterKey.Builder(this).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();return EncryptedSharedPreferences.create(this,"vault",k,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM);}catch(Exception e){return getSharedPreferences("vault_fallback",MODE_PRIVATE);}}
  GradientDrawable shape(int color,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(22);g.setStroke(2,stroke);return g;}
  TextView tv(String s,int n){TextView v=new TextView(this);v.setText(s);v.setTextColor(FG);v.setTextSize(n);v.setPadding(20,16,20,16);return v;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(FG);b.setAllCaps(false);b.setTextSize(14);b.setBackground(shape(CARD,ORANGE));b.setPadding(18,12,18,12);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.setMargins(5,6,5,6);b.setLayoutParams(lp);return b;}
  EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(FG);e.setHintTextColor(Color.GRAY);e.setBackground(shape(CARD,Color.rgb(75,65,55)));e.setPadding(20,17,20,17);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,7,0,7);e.setLayoutParams(lp);return e;}
  void home(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);TextView brand=tv("◉ AURION ONE  •  MOBILE CORE",23);brand.setTextColor(ORANGE);root.addView(brand);status=tv(diag(),12);root.addView(status);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout nav=new LinearLayout(this);String[] ns={"Início","Chat","Voz","Memória","Criar","Estúdio","Imagem","Converter","Modelos","Conexões","PC","Bíblia","Contas"};for(String n:ns){Button b=btn(n);b.setOnClickListener(v->screen(n));nav.addView(b);}hs.addView(nav);root.addView(hs);ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(18,12,18,40);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);screen("Início");}
  void clear(String title){body.removeAllViews();body.addView(tv(title,21));}
  void screen(String s){if(s.equals("Início"))dashboard();else if(s.equals("Chat"))chat();else if(s.equals("Voz"))voice();else if(s.equals("Memória"))memory();else if(s.equals("Criar"))create();else if(s.equals("Estúdio"))studio();else if(s.equals("Imagem"))imageLab();else if(s.equals("Converter"))converter();else if(s.equals("Modelos"))models();else if(s.equals("Conexões"))connections();else if(s.equals("PC"))pc();else if(s.equals("Bíblia"))docs();else accounts();}
  void dashboard(){clear("Painel central");body.addView(card("IA ATIVA",providerSummary()));body.addView(card("MEMÓRIA",secrets.getStringSet("memories",new LinkedHashSet<>()).size()+" caixas persistentes"));body.addView(card("ESTÚDIO","Imagem local pronta • montagem avançada em evolução"));body.addView(card("CONEXÕES","GitHub/Drive por acesso autorizado • PC opcional"));Button talk=btn("🎙 Falar com AURION");talk.setOnClickListener(v->{screen("Chat");listen();});body.addView(talk);}
  TextView card(String title,String text){TextView v=tv(title+"\n"+text,16);v.setBackground(shape(CARD,Color.rgb(79,57,36)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,8,0,8);v.setLayoutParams(lp);return v;}
  String providerSummary(){String[] p={"groq","xai","silicon","pollinations","hf","custom"};StringBuilder s=new StringBuilder();for(String x:p)if(!secrets.getString(x+"_key","").isEmpty())s.append(x).append(" conectado  ");return s.length()==0?"Nenhum provedor configurado":s.toString();}
  void chat(){clear("Chat inteligente + voz");output=tv("Configure endpoint, chave e modelo em Contas. O microfone do fone Bluetooth é usado pelo Android quando estiver selecionado como entrada.",16);body.addView(output);input=field("Fale ou escreva sua mensagem");body.addView(input);LinearLayout r=new LinearLayout(this);Button mic=btn("🎙 Voz");mic.setOnClickListener(v->listen());Button send=btn("Enviar");send.setOnClickListener(v->chatRequest());r.addView(mic,new LinearLayout.LayoutParams(0,-2,1));r.addView(send,new LinearLayout.LayoutParams(0,-2,1));body.addView(r);}
  void chatRequest(){String q=input.getText().toString().trim();if(q.isEmpty())return;output.setText("AURION escolhendo a melhor rota...");try{JSONArray a=new JSONArray();a.put(new JSONObject().put("role","system").put("content","Você é AURION ONE. Responda em português, preserve o contexto do operador e seja objetivo."));for(String m:secrets.getStringSet("memories",new LinkedHashSet<>()))a.put(new JSONObject().put("role","system").put("content","Memória autorizada: "+m));a.put(new JSONObject().put("role","user").put("content",q));smartTry(new String[]{"groq","xai","silicon","pollinations","hf","custom"},0,a);}catch(Exception e){output.setText(e.toString());}}
  void smartTry(String[] order,int pos,JSONArray messages){if(pos>=order.length){ui(()->output.setText("Todos os provedores configurados falharam ou estão sem cota. Verifique Contas."));return;}String p=order[pos],url=secrets.getString(p+"_url",""),key=secrets.getString(p+"_key",""),model=secrets.getString(p+"_model","");if(url.isEmpty()||key.isEmpty()){smartTry(order,pos+1,messages);return;}try{JSONObject j=new JSONObject().put("model",model).put("messages",messages);postStatus(url,key,j,(code,res)->{if(code>=200&&code<300){try{String x=new JSONObject(res).getJSONArray("choices").getJSONObject(0).getJSONObject("message").getString("content");markProvider(p,true);ui(()->{output.setText("Rota: "+p+"\n\n"+x);speak(x);});}catch(Exception e){markProvider(p,false);smartTry(order,pos+1,messages);}}else{markProvider(p,false);ui(()->output.setText("Rota "+p+" indisponível ("+code+"). Tentando outra..."));smartTry(order,pos+1,messages);}});}catch(Exception e){smartTry(order,pos+1,messages);}}
  void markProvider(String p,boolean ok){int n=secrets.getInt("stat_"+p+(ok?"_ok":"_fail"),0)+1;secrets.edit().putInt("stat_"+p+(ok?"_ok":"_fail"),n).apply();}
  void voice(){clear("Voz e capacete");body.addView(card("BOTÃO DO FONE","Play/Pause ou botão do headset chama o microfone enquanto o AURION estiver ativo."));Button settings=btn("Configurar vozes do Android");settings.setOnClickListener(v->{try{startActivity(new Intent("com.android.settings.TTS_SETTINGS"));}catch(Exception e){toast("Abra Configurações > Texto para fala");}});body.addView(settings);SeekBar rate=new SeekBar(this);rate.setMax(150);rate.setProgress((int)(secrets.getFloat("voice_rate",1f)*100-50));body.addView(tv("Velocidade da voz",14));body.addView(rate);SeekBar pitch=new SeekBar(this);pitch.setMax(150);pitch.setProgress((int)(secrets.getFloat("voice_pitch",1f)*100-50));body.addView(tv("Tom da voz",14));body.addView(pitch);Button save=btn("Salvar voz e testar");save.setOnClickListener(v->{voiceRate=(rate.getProgress()+50)/100f;voicePitch=(pitch.getProgress()+50)/100f;secrets.edit().putFloat("voice_rate",voiceRate).putFloat("voice_pitch",voicePitch).apply();tts.setSpeechRate(voiceRate);tts.setPitch(voicePitch);speak("AURION ONE pronto para o capacete.");});body.addView(save);Button mic=btn("🎙 Testar microfone agora");mic.setOnClickListener(v->{screen("Chat");listen();});body.addView(mic);body.addView(tv("Clonagem/treino de voz exige um provedor específico e consentimento da pessoa. Aqui você escolhe e regula as vozes instaladas no POCO.",13));}
  void memory(){clear("Caixas de memória");EditText e=field("Nova memória autorizada: projeto, preferência ou regra");body.addView(e);Button add=btn("＋ Guardar caixa");add.setOnClickListener(v->{String x=e.getText().toString().trim();if(x.isEmpty())return;Set<String> m=new LinkedHashSet<>(secrets.getStringSet("memories",new LinkedHashSet<>()));m.add(x);secrets.edit().putStringSet("memories",m).apply();memory();});body.addView(add);Set<String> ms=new LinkedHashSet<>(secrets.getStringSet("memories",new LinkedHashSet<>()));for(String x:ms){TextView c=card("MEMÓRIA",x);c.setOnLongClickListener(v->{Set<String> m=new LinkedHashSet<>(secrets.getStringSet("memories",new LinkedHashSet<>()));m.remove(x);secrets.edit().putStringSet("memories",m).apply();memory();return true;});body.addView(c);}body.addView(tv("Segure uma caixa para apagar. Estas memórias ficam no aparelho e entram no contexto do chat.",13));}
  void create(){clear("Imagem e vídeo");TextView info=tv("Usa endpoints de nuvem configurados. Qwen-Image, Wan e MiniMax completos não rodam localmente de forma prática no POCO X7.",15);body.addView(info);EditText p=field("Descreva a imagem ou vídeo");body.addView(p);Button im=btn("Gerar imagem");im.setOnClickListener(v->generation("image",p.getText().toString()));body.addView(im);Button vi=btn("Gerar vídeo");vi.setOnClickListener(v->generation("video",p.getText().toString()));body.addView(vi);output=tv("O resultado bruto/URL aparecerá aqui.",14);body.addView(output);}
  void generation(String kind,String prompt){String url=secrets.getString(kind+"_url",""),key=secrets.getString(kind+"_key",secrets.getString("hf_key","")),model=secrets.getString(kind+"_model","");if(url.isEmpty()||key.isEmpty()){toast("Configure endpoint e chave em Contas");return;}output.setText("Enviando...");try{JSONObject j=new JSONObject().put("model",model).put("prompt",prompt).put("inputs",prompt);post(url,key,j,res->ui(()->output.setText(res)));}catch(Exception e){output.setText(e.toString());}}
  void studio(){clear("Estúdio de montagem");body.addView(tv("Selecione imagens, vídeos e áudios. A fila registra os itens e prepara o projeto; renderização avançada com transições/LUT será adicionada pelo motor Media3.",15));Button pick=btn("Carregar mídia");pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_MEDIA);});body.addView(pick);output=tv("Itens selecionados: "+mediaCount,15);body.addView(output);Button share=btn("Enviar projeto para editor instalado");share.setOnClickListener(v->toast("Selecione a mídia primeiro; integração não destrutiva preparada."));body.addView(share);body.addView(tv("Fila futura: cortes • áudio • transições • LUT • legendas • exportação MP4.",14));}
  void imageLab(){clear("Tratamento de imagem local");Button pick=btn("Abrir imagem");pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*");startActivityForResult(i,PICK_IMAGE);});body.addView(pick);preview=new ImageView(this);preview.setAdjustViewBounds(true);body.addView(preview);LinearLayout r=new LinearLayout(this);Button auto=btn("Contraste");auto.setOnClickListener(v->filter(false));Button gray=btn("P&B");gray.setOnClickListener(v->filter(true));r.addView(auto,new LinearLayout.LayoutParams(0,-2,1));r.addView(gray,new LinearLayout.LayoutParams(0,-2,1));body.addView(r);Button save=btn("Salvar JPG tratado");save.setOnClickListener(v->saveBitmap());body.addView(save);}
  void filter(boolean gray){if(workingBitmap==null){toast("Abra uma imagem");return;}Bitmap out=Bitmap.createBitmap(workingBitmap.getWidth(),workingBitmap.getHeight(),Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);Paint p=new Paint();ColorMatrix m=new ColorMatrix();if(gray)m.setSaturation(0);else m.set(new float[]{1.18f,0,0,0,-12,0,1.18f,0,0,-12,0,0,1.18f,0,-12,0,0,0,1,0});p.setColorFilter(new ColorMatrixColorFilter(m));c.drawBitmap(workingBitmap,0,0,p);workingBitmap=out;preview.setImageBitmap(out);}
  void saveBitmap(){if(workingBitmap==null){toast("Abra uma imagem");return;}try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"AURION_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/AURION");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);try(OutputStream o=getContentResolver().openOutputStream(u)){workingBitmap.compress(Bitmap.CompressFormat.JPEG,94,o);}toast("Imagem salva em Pictures/AURION");}catch(Exception e){toast("Falha ao salvar: "+e.getMessage());}}
  void converter(){clear("Conversões");body.addView(tv("Conversão local de imagem está ativa na aba Imagem: JPG com qualidade 94. As rotas PNG, WEBP, áudio e vídeo serão ligadas ao mesmo projeto sem enviar seus arquivos para terceiros.",15));Button go=btn("Abrir tratamento de imagem");go.setOnClickListener(v->imageLab());body.addView(go);}
  void pc(){clear("PC, GPU e armazenamento");body.addView(tv("Porta opcional para usar ComfyUI, Ollama ou AURION no PC. O aplicativo continua funcionando sem o PC.",15));addSecret("pc_url","URL segura do PC, ex.: https://nome.ts.net:8765");addSecret("pc_key","Token do agente PC");Button test=btn("Testar conexão /health");test.setOnClickListener(v->{String u=secrets.getString("pc_url","");if(u.isEmpty()){toast("Cadastre a URL");return;}get(u+"/health",secrets.getString("pc_key",""),res->ui(()->{output.setText(res);toast("Resposta recebida");}));});body.addView(test);output=tv("Aguardando teste.",14);body.addView(output);}
  void connections(){clear("Conexões autorizadas");body.addView(card("GOOGLE DRIVE","Importação pelo seletor oficial do Android; o AURION só recebe o arquivo escolhido."));Button drive=btn("Abrir meu Drive");drive.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_DRIVE);});body.addView(drive);body.addView(card("GITHUB","Repositório oficial e configuração por token ficam separados."));Button git=btn("Abrir AURION-ONE no GitHub");git.setOnClickListener(v->open("https://github.com/cleitongoy-debug/AURION-ONE"));body.addView(git);addSecret("github_token","Token GitHub opcional");addSecret("github_repo","Repositório owner/name");Button check=btn("Testar GitHub");check.setOnClickListener(v->get("https://api.github.com/repos/"+secrets.getString("github_repo","cleitongoy-debug/AURION-ONE"),secrets.getString("github_token",""),res->ui(()->toast(res.startsWith("Falha")?res:"GitHub respondeu"))));body.addView(check);}
  void docs(){clear("Bíblia, reuniões e verdade operacional");body.addView(card("MANDAMENTOS","Não inventar funcionamento; proteger segredos; preservar trabalhos; testar cada ação."));body.addView(card("REUNIÕES","POCO é independente; PC/GPU é rota opcional autenticada; estados precisam de verificação real."));Button bible=btn("Abrir documentos no GitHub");bible.setOnClickListener(v->open("https://github.com/cleitongoy-debug/AURION-ONE/tree/main/docs"));body.addView(bible);}
  void models(){clear("Modelos e arquivos");body.addView(tv("Baixe somente GGUF compatível e arquivos de fontes confiáveis. O gerenciador usa o DownloadManager do Android, mostra a notificação e permite retomar pelo sistema.",15));EditText url=field("URL HTTPS do Hugging Face ou GitHub");body.addView(url);EditText name=field("Nome do arquivo, ex.: modelo.gguf");body.addView(name);Button d=btn("Baixar arquivo");d.setOnClickListener(v->download(url.getText().toString(),name.getText().toString()));body.addView(d);Button hf=btn("Abrir Hugging Face");hf.setOnClickListener(v->open("https://huggingface.co/models?library=gguf"));body.addView(hf);Button gh=btn("Abrir GitHub");gh.setOnClickListener(v->open("https://github.com"));body.addView(gh);body.addView(tv("Importante: esta versão gerencia os modelos. O motor local GGUF ainda não está embutido; chat funciona pelo endpoint configurado.",14));}
  void accounts(){clear("Contas, rotas e cotas");body.addView(tv("O roteador tenta Groq → Grok/xAI → SiliconFlow → Pollinations → Hugging Face → personalizado.",14));preset("groq","Groq Free","https://api.groq.com/openai/v1/chat/completions","qwen/qwen3.8-27b");preset("xai","Grok / xAI","https://api.x.ai/v1/chat/completions","grok-4.7");preset("silicon","SiliconFlow / Qwen","https://api.siliconflow.com/v1/chat/completions","Qwen/Qwen3-8B");preset("pollinations","Pollinations","https://gen.pollinations.ai/v1/chat/completions","openai");preset("hf","Hugging Face","https://router.huggingface.co/v1/chat/completions","Qwen/Qwen2.5-7B-Instruct");preset("custom","Personalizado/PC","","");addSecret("image_url","Endpoint de imagem");addSecret("image_key","Chave de imagem");addSecret("image_model","Modelo de imagem");addSecret("video_url","Endpoint de vídeo");addSecret("video_key","Chave de vídeo");addSecret("video_model","Modelo de vídeo");Button test=btn("Salvar e testar no Chat");test.setOnClickListener(v->screen("Chat"));body.addView(test);}
  void preset(String id,String label,String defUrl,String defModel){body.addView(tv(label+" • êxitos "+secrets.getInt("stat_"+id+"_ok",0)+" • falhas "+secrets.getInt("stat_"+id+"_fail",0),16));if(!secrets.contains(id+"_url"))secrets.edit().putString(id+"_url",defUrl).putString(id+"_model",defModel).apply();addSecret(id+"_key",label+" — chave");addSecret(id+"_url",label+" — endpoint");addSecret(id+"_model",label+" — modelo");}
  void addSecret(String key,String label){EditText e=field(label);e.setText(secrets.getString(key,""));if(key.contains("key"))e.setInputType(129);e.setOnFocusChangeListener((v,has)->{if(!has)secrets.edit().putString(key,e.getText().toString().trim()).apply();});body.addView(e);}
  void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("Reconhecimento de voz indisponível");return;}sr=SpeechRecognizer.createSpeechRecognizer(this);sr.setRecognitionListener(new android.speech.RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float f){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){toast("Voz: erro "+e);}public void onResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty()){input.setText(x.get(0));chatRequest();}}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"pt-BR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);sr.startListening(i);toast("Ouvindo...");}
  void post(String endpoint,String key,JSONObject payload,java.util.function.Consumer<String> done){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(20000);c.setReadTimeout(120000);c.setRequestMethod("POST");c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(payload.toString().getBytes(StandardCharsets.UTF_8));}InputStream in=(c.getResponseCode()<400?c.getInputStream():c.getErrorStream());String res=read(in);done.accept(res);}catch(Exception e){ui(()->{if(output!=null)output.setText("Falha: "+e.getMessage());});}}).start();}
  interface StatusCallback{void done(int code,String body);}
  void postStatus(String endpoint,String key,JSONObject payload,StatusCallback done){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(90000);c.setRequestMethod("POST");c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(payload.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();done.done(code,read(code<400?c.getInputStream():c.getErrorStream()));}catch(Exception e){done.done(599,e.getMessage());}}).start();}
  void get(String endpoint,String key,java.util.function.Consumer<String> done){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(30000);if(!key.isEmpty())c.setRequestProperty("Authorization","Bearer "+key);done.accept(read(c.getInputStream()));}catch(Exception e){done.accept("Falha: "+e.getMessage());}}).start();}
  String read(InputStream i)throws Exception{BufferedReader b=new BufferedReader(new InputStreamReader(i,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l).append('\n');return s.toString();}
  void download(String u,String n){try{Uri x=Uri.parse(u);if(!"https".equals(x.getScheme()))throw new Exception("Use HTTPS");if(n.trim().isEmpty())n=x.getLastPathSegment();DownloadManager.Request r=new DownloadManager.Request(x).setTitle(n).setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED).setDestinationInExternalFilesDir(this,android.os.Environment.DIRECTORY_DOWNLOADS,n);((DownloadManager)getSystemService(DOWNLOAD_SERVICE)).enqueue(r);toast("Download iniciado");}catch(Exception e){toast("URL inválida: "+e.getMessage());}}
  String diag(){return Build.MANUFACTURER+" "+Build.MODEL+" • Android "+Build.VERSION.RELEASE+" • "+(Runtime.getRuntime().maxMemory()/1048576)+" MB por processo";}
  void open(String u){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}void ui(Runnable r){runOnUiThread(r);}void toast(String s){ui(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}void speak(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"aurion");}
  public void onInit(int x){if(x==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("pt","BR"));voiceRate=secrets.getFloat("voice_rate",1f);voicePitch=secrets.getFloat("voice_pitch",1f);tts.setSpeechRate(voiceRate);tts.setPitch(voicePitch);}}
  void setupMediaButtons(){mediaSession=new MediaSession(this,"AURIONHeadset");mediaSession.setCallback(new MediaSession.Callback(){@Override public boolean onMediaButtonEvent(Intent i){ui(()->{screen("Chat");listen();});return true;}});mediaSession.setActive(true);}
  @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;try{if(request==PICK_IMAGE&&data.getData()!=null){try(InputStream in=getContentResolver().openInputStream(data.getData())){workingBitmap=BitmapFactory.decodeStream(in);}if(preview!=null)preview.setImageBitmap(workingBitmap);}else if(request==PICK_MEDIA){mediaCount=data.getClipData()!=null?data.getClipData().getItemCount():(data.getData()!=null?1:0);if(output!=null)output.setText("Itens selecionados: "+mediaCount);}}catch(Exception e){toast("Falha ao abrir mídia: "+e.getMessage());}}
  @Override protected void onDestroy(){if(sr!=null)sr.destroy();if(tts!=null)tts.shutdown();if(mediaSession!=null)mediaSession.release();super.onDestroy();}
}
