package one.aurion.mobileai;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.ColorMatrix;
import android.graphics.ColorMatrixColorFilter;
import android.graphics.Paint;
import android.net.Uri;
import android.os.*;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.speech.tts.TextToSpeech;
import android.view.*;
import android.widget.*;
import android.provider.MediaStore;
import android.content.ContentValues;
import android.text.method.LinkMovementMethod;
import androidx.security.crypto.EncryptedSharedPreferences;
import androidx.security.crypto.MasterKey;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class MainActivity extends Activity implements TextToSpeech.OnInitListener {
  static final int MIC=70, PICK_IMAGE=71, PICK_MEDIA=72; final int BG=Color.rgb(7,17,31), CARD=Color.rgb(17,35,58), FG=Color.WHITE;
  LinearLayout root, body; EditText input; TextView output, status; SharedPreferences secrets; TextToSpeech tts; SpeechRecognizer sr; Bitmap workingBitmap; ImageView preview; int mediaCount=0;
  @Override public void onCreate(Bundle b){super.onCreate(b); secrets=secure(); tts=new TextToSpeech(this,this); home();}
  SharedPreferences secure(){try{MasterKey k=new MasterKey.Builder(this).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();return EncryptedSharedPreferences.create(this,"vault",k,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM);}catch(Exception e){return getSharedPreferences("vault_fallback",MODE_PRIVATE);}}
  TextView tv(String s,int n){TextView v=new TextView(this);v.setText(s);v.setTextColor(FG);v.setTextSize(n);v.setPadding(18,15,18,15);return v;}
  Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
  EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextColor(FG);e.setHintTextColor(Color.LTGRAY);e.setBackgroundColor(CARD);e.setPadding(18,16,18,16);return e;}
  void home(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.addView(tv("AURION MOBILE AI • X7 PRO",24));status=tv(diag(),12);root.addView(status);HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout nav=new LinearLayout(this);String[] ns={"Chat","Criar","Estúdio","Imagem","Converter","Modelos","PC","Contas"};for(String n:ns){Button b=btn(n);b.setOnClickListener(v->screen(n));nav.addView(b);}hs.addView(nav);root.addView(hs);ScrollView sc=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(16,12,16,30);sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);screen("Chat");}
  void clear(String title){body.removeAllViews();body.addView(tv(title,21));}
  void screen(String s){if(s.equals("Chat"))chat();else if(s.equals("Criar"))create();else if(s.equals("Estúdio"))studio();else if(s.equals("Imagem"))imageLab();else if(s.equals("Converter"))converter();else if(s.equals("Modelos"))models();else if(s.equals("PC"))pc();else accounts();}
  void chat(){clear("Chat inteligente + voz");output=tv("Configure endpoint, chave e modelo em Contas. O microfone do fone Bluetooth é usado pelo Android quando estiver selecionado como entrada.",16);body.addView(output);input=field("Fale ou escreva sua mensagem");body.addView(input);LinearLayout r=new LinearLayout(this);Button mic=btn("🎙 Voz");mic.setOnClickListener(v->listen());Button send=btn("Enviar");send.setOnClickListener(v->chatRequest());r.addView(mic,new LinearLayout.LayoutParams(0,-2,1));r.addView(send,new LinearLayout.LayoutParams(0,-2,1));body.addView(r);}
  void chatRequest(){String q=input.getText().toString().trim();if(q.isEmpty())return;output.setText("AURION escolhendo a melhor rota...");try{JSONArray a=new JSONArray();a.put(new JSONObject().put("role","system").put("content","Você é AURION, assistente objetivo em português."));a.put(new JSONObject().put("role","user").put("content",q));smartTry(new String[]{"groq","silicon","pollinations","hf","custom"},0,a);}catch(Exception e){output.setText(e.toString());}}
  void smartTry(String[] order,int pos,JSONArray messages){if(pos>=order.length){ui(()->output.setText("Todos os provedores configurados falharam ou estão sem cota. Verifique Contas."));return;}String p=order[pos],url=secrets.getString(p+"_url",""),key=secrets.getString(p+"_key",""),model=secrets.getString(p+"_model","");if(url.isEmpty()||key.isEmpty()){smartTry(order,pos+1,messages);return;}try{JSONObject j=new JSONObject().put("model",model).put("messages",messages);postStatus(url,key,j,(code,res)->{if(code>=200&&code<300){try{String x=new JSONObject(res).getJSONArray("choices").getJSONObject(0).getJSONObject("message").getString("content");markProvider(p,true);ui(()->{output.setText("Rota: "+p+"\n\n"+x);speak(x);});}catch(Exception e){markProvider(p,false);smartTry(order,pos+1,messages);}}else{markProvider(p,false);ui(()->output.setText("Rota "+p+" indisponível ("+code+"). Tentando outra..."));smartTry(order,pos+1,messages);}});}catch(Exception e){smartTry(order,pos+1,messages);}}
  void markProvider(String p,boolean ok){int n=secrets.getInt("stat_"+p+(ok?"_ok":"_fail"),0)+1;secrets.edit().putInt("stat_"+p+(ok?"_ok":"_fail"),n).apply();}
  void create(){clear("Imagem e vídeo");TextView info=tv("Usa endpoints de nuvem configurados. Qwen-Image, Wan e MiniMax completos não rodam localmente de forma prática no POCO X7.",15);body.addView(info);EditText p=field("Descreva a imagem ou vídeo");body.addView(p);Button im=btn("Gerar imagem");im.setOnClickListener(v->generation("image",p.getText().toString()));body.addView(im);Button vi=btn("Gerar vídeo");vi.setOnClickListener(v->generation("video",p.getText().toString()));body.addView(vi);output=tv("O resultado bruto/URL aparecerá aqui.",14);body.addView(output);}
  void generation(String kind,String prompt){String url=secrets.getString(kind+"_url",""),key=secrets.getString(kind+"_key",secrets.getString("hf_key","")),model=secrets.getString(kind+"_model","");if(url.isEmpty()||key.isEmpty()){toast("Configure endpoint e chave em Contas");return;}output.setText("Enviando...");try{JSONObject j=new JSONObject().put("model",model).put("prompt",prompt).put("inputs",prompt);post(url,key,j,res->ui(()->output.setText(res)));}catch(Exception e){output.setText(e.toString());}}
  void studio(){clear("Estúdio de montagem");body.addView(tv("Selecione imagens, vídeos e áudios. A fila registra os itens e prepara o projeto; renderização avançada com transições/LUT será adicionada pelo motor Media3.",15));Button pick=btn("Carregar mídia");pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_MEDIA);});body.addView(pick);output=tv("Itens selecionados: "+mediaCount,15);body.addView(output);Button share=btn("Enviar projeto para editor instalado");share.setOnClickListener(v->toast("Selecione a mídia primeiro; integração não destrutiva preparada."));body.addView(share);body.addView(tv("Fila futura: cortes • áudio • transições • LUT • legendas • exportação MP4.",14));}
  void imageLab(){clear("Tratamento de imagem local");Button pick=btn("Abrir imagem");pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*");startActivityForResult(i,PICK_IMAGE);});body.addView(pick);preview=new ImageView(this);preview.setAdjustViewBounds(true);body.addView(preview);LinearLayout r=new LinearLayout(this);Button auto=btn("Contraste");auto.setOnClickListener(v->filter(false));Button gray=btn("P&B");gray.setOnClickListener(v->filter(true));r.addView(auto,new LinearLayout.LayoutParams(0,-2,1));r.addView(gray,new LinearLayout.LayoutParams(0,-2,1));body.addView(r);Button save=btn("Salvar JPG tratado");save.setOnClickListener(v->saveBitmap());body.addView(save);}
  void filter(boolean gray){if(workingBitmap==null){toast("Abra uma imagem");return;}Bitmap out=Bitmap.createBitmap(workingBitmap.getWidth(),workingBitmap.getHeight(),Bitmap.Config.ARGB_8888);Canvas c=new Canvas(out);Paint p=new Paint();ColorMatrix m=new ColorMatrix();if(gray)m.setSaturation(0);else m.set(new float[]{1.18f,0,0,0,-12,0,1.18f,0,0,-12,0,0,1.18f,0,-12,0,0,0,1,0});p.setColorFilter(new ColorMatrixColorFilter(m));c.drawBitmap(workingBitmap,0,0,p);workingBitmap=out;preview.setImageBitmap(out);}
  void saveBitmap(){if(workingBitmap==null){toast("Abra uma imagem");return;}try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"AURION_"+System.currentTimeMillis()+".jpg");v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/AURION");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);try(OutputStream o=getContentResolver().openOutputStream(u)){workingBitmap.compress(Bitmap.CompressFormat.JPEG,94,o);}toast("Imagem salva em Pictures/AURION");}catch(Exception e){toast("Falha ao salvar: "+e.getMessage());}}
  void converter(){clear("Conversões");body.addView(tv("Conversão local de imagem está ativa na aba Imagem: JPG com qualidade 94. As rotas PNG, WEBP, áudio e vídeo serão ligadas ao mesmo projeto sem enviar seus arquivos para terceiros.",15));Button go=btn("Abrir tratamento de imagem");go.setOnClickListener(v->imageLab());body.addView(go);}
  void pc(){clear("PC, GPU e armazenamento");body.addView(tv("Porta opcional para usar ComfyUI, Ollama ou AURION no PC. O aplicativo continua funcionando sem o PC.",15));addSecret("pc_url","URL segura do PC, ex.: https://nome.ts.net:8765");addSecret("pc_key","Token do agente PC");Button test=btn("Testar conexão /health");test.setOnClickListener(v->{String u=secrets.getString("pc_url","");if(u.isEmpty()){toast("Cadastre a URL");return;}get(u+"/health",secrets.getString("pc_key",""),res->ui(()->{output.setText(res);toast("Resposta recebida");}));});body.addView(test);output=tv("Aguardando teste.",14);body.addView(output);}
  void models(){clear("Modelos e arquivos");body.addView(tv("Baixe somente GGUF compatível e arquivos de fontes confiáveis. O gerenciador usa o DownloadManager do Android, mostra a notificação e permite retomar pelo sistema.",15));EditText url=field("URL HTTPS do Hugging Face ou GitHub");body.addView(url);EditText name=field("Nome do arquivo, ex.: modelo.gguf");body.addView(name);Button d=btn("Baixar arquivo");d.setOnClickListener(v->download(url.getText().toString(),name.getText().toString()));body.addView(d);Button hf=btn("Abrir Hugging Face");hf.setOnClickListener(v->open("https://huggingface.co/models?library=gguf"));body.addView(hf);Button gh=btn("Abrir GitHub");gh.setOnClickListener(v->open("https://github.com"));body.addView(gh);body.addView(tv("Importante: esta versão gerencia os modelos. O motor local GGUF ainda não está embutido; chat funciona pelo endpoint configurado.",14));}
  void accounts(){clear("Contas, rotas e cotas");body.addView(tv("O roteador tenta Groq → SiliconFlow → Pollinations → Hugging Face → personalizado. Chaves ficam criptografadas no Android.",14));preset("groq","Groq Free","https://api.groq.com/openai/v1/chat/completions","qwen/qwen3.8-27b");preset("silicon","SiliconFlow / Qwen","https://api.siliconflow.com/v1/chat/completions","Qwen/Qwen3-8B");preset("pollinations","Pollinations","https://gen.pollinations.ai/v1/chat/completions","openai");preset("hf","Hugging Face","https://router.huggingface.co/v1/chat/completions","Qwen/Qwen2.5-7B-Instruct");preset("custom","Personalizado/PC","","");addSecret("image_url","Endpoint de imagem");addSecret("image_key","Chave de imagem");addSecret("image_model","Modelo de imagem");addSecret("video_url","Endpoint de vídeo");addSecret("video_key","Chave de vídeo");addSecret("video_model","Modelo de vídeo");Button test=btn("Salvar e testar no Chat");test.setOnClickListener(v->screen("Chat"));body.addView(test);}
  void preset(String id,String label,String defUrl,String defModel){body.addView(tv(label+" • êxitos "+secrets.getInt("stat_"+id+"_ok",0)+" • falhas "+secrets.getInt("stat_"+id+"_fail",0),16));if(!secrets.contains(id+"_url"))secrets.edit().putString(id+"_url",defUrl).putString(id+"_model",defModel).apply();addSecret(id+"_key",label+" — chave");addSecret(id+"_url",label+" — endpoint");addSecret(id+"_model",label+" — modelo");}
  void addSecret(String key,String label){EditText e=field(label);e.setText(secrets.getString(key,""));if(key.contains("key"))e.setInputType(129);e.setOnFocusChangeListener((v,has)->{if(!has)secrets.edit().putString(key,e.getText().toString().trim()).apply();});body.addView(e);}
  void listen(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},MIC);return;}if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("Reconhecimento de voz indisponível");return;}sr=SpeechRecognizer.createSpeechRecognizer(this);sr.setRecognitionListener(new android.speech.RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float f){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){toast("Voz: erro "+e);}public void onResults(Bundle b){ArrayList<String>x=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x!=null&&!x.isEmpty()){input.setText(x.get(0));chatRequest();}}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"pt-BR");i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);sr.startListening(i);toast("Ouvindo...");}
  void post(String endpoint,String key,JSONObject payload,java.util.function.Consumer<String> done){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(20000);c.setReadTimeout(120000);c.setRequestMethod("POST");c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(payload.toString().getBytes(StandardCharsets.UTF_8));}InputStream in=(c.getResponseCode()<400?c.getInputStream():c.getErrorStream());String res=read(in);done.accept(res);}catch(Exception e){ui(()->{if(output!=null)output.setText("Falha: "+e.getMessage());});}}).start();}
  interface StatusCallback{void done(int code,String body);}
  void postStatus(String endpoint,String key,JSONObject payload,StatusCallback done){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(90000);c.setRequestMethod("POST");c.setRequestProperty("Authorization","Bearer "+key);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(payload.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();done.done(code,read(code<400?c.getInputStream():c.getErrorStream()));}catch(Exception e){done.done(599,e.getMessage());}}).start();}
  void get(String endpoint,String key,java.util.function.Consumer<String> done){new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(30000);if(!key.isEmpty())c.setRequestProperty("Authorization","Bearer "+key);done.accept(read(c.getInputStream()));}catch(Exception e){done.accept("Falha: "+e.getMessage());}}).start();}
  String read(InputStream i)throws Exception{BufferedReader b=new BufferedReader(new InputStreamReader(i,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l).append('\n');return s.toString();}
  void download(String u,String n){try{Uri x=Uri.parse(u);if(!"https".equals(x.getScheme()))throw new Exception("Use HTTPS");if(n.trim().isEmpty())n=x.getLastPathSegment();DownloadManager.Request r=new DownloadManager.Request(x).setTitle(n).setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED).setDestinationInExternalFilesDir(this,android.os.Environment.DIRECTORY_DOWNLOADS,n);((DownloadManager)getSystemService(DOWNLOAD_SERVICE)).enqueue(r);toast("Download iniciado");}catch(Exception e){toast("URL inválida: "+e.getMessage());}}
  String diag(){return Build.MANUFACTURER+" "+Build.MODEL+" • Android "+Build.VERSION.RELEASE+" • "+(Runtime.getRuntime().maxMemory()/1048576)+" MB por processo";}
  void open(String u){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}void ui(Runnable r){runOnUiThread(r);}void toast(String s){ui(()->Toast.makeText(this,s,Toast.LENGTH_LONG).show());}void speak(String s){if(tts!=null)tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"aurion");}
  public void onInit(int x){if(x==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("pt","BR"));}
  @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;try{if(request==PICK_IMAGE&&data.getData()!=null){try(InputStream in=getContentResolver().openInputStream(data.getData())){workingBitmap=BitmapFactory.decodeStream(in);}if(preview!=null)preview.setImageBitmap(workingBitmap);}else if(request==PICK_MEDIA){mediaCount=data.getClipData()!=null?data.getClipData().getItemCount():(data.getData()!=null?1:0);if(output!=null)output.setText("Itens selecionados: "+mediaCount);}}catch(Exception e){toast("Falha ao abrir mídia: "+e.getMessage());}}
  @Override protected void onDestroy(){if(sr!=null)sr.destroy();if(tts!=null)tts.shutdown();super.onDestroy();}
}
