"""Patch idempotente: amplia a aba História sem tocar em tokens, outras abas ou APK.
Dados publicados: agregados historicos previamente documentados e logs especificos.
"""
from pathlib import Path

p = Path(__file__).resolve().parents[1] / 'mobile' / 'aurion-one-live.html'
s = p.read_text(encoding='utf-8')
marker = '<p class="muted">Os três valores de 2025 são <strong>snapshots históricos declarados</strong>.'
flag = 'id="historia-cruzada-v2"'
assert s.count(marker) == 1, 'Marcador da História alterado; nenhum arquivo modificado'
if flag not in s:
    block = '''<div class="card" id="historia-cruzada-v2"><h2>Rastros cruzados · DigitalPen / AURION / agentes</h2><p class="muted">Marcos distintos documentados em arquivos do Drive. Cópias e snapshots espelhados são mostrados como a mesma evidência; nenhum número é telemetria em tempo real.</p><div class="gauges"><div class="gauge"><div class="name">Evolução declarada do núcleo</div><div class="value">+2.049 ciclos</div><small>4.833 (snapshot anterior de novembro/2025) → 6.882 (12/11/2025). Diferença entre registros, não ciclos comprovados por execução.</small></div><div class="gauge"><div class="name">Sincronização Q9 · 04/11/2025</div><div class="value">41 / 41</div><small>SYNC_DONE e EXPORT_DONE no mesmo log; 41 itens nesta execução, não 82 trabalhos nem 41 horas.</small></div><div class="gauge"><div class="name">JSON_13 · agente</div><div class="value">128,43 h</div><small>Contador automático declarado no snapshot anterior; não é tempo humano.</small></div><div class="gauge"><div class="name">GR_BAT_32_ST · agente</div><div class="value">43,43 h</div><small>Contador automático declarado no mesmo snapshot.</small></div><div class="gauge"><div class="name">BB_MANAGER · agente</div><div class="value">23,42 h</div><small>Contador automático declarado no mesmo snapshot.</small></div><div class="gauge"><div class="name">Agentes · soma nominal</div><div class="value">195,28 h</div><small>128,43 + 43,43 + 23,42. Soma de contadores distintos, NÃO tempo decorrido ou esforço humano: execução paralela pode se sobrepor.</small></div><div class="gauge wide"><div class="name">DS20 · snapshot anterior</div><div class="value">63,43 h</div><small>Registro separado do início de novembro. No snapshot posterior as horas aparecem espelhadas às do núcleo; NÃO somar ao total de 315,7 h.</small></div></div><h3>Marcos com registro</h3><p><strong>Outubro/2025:</strong> implantação inicial DigitalPen descrita no dossiê; log Q-05 de 19/10/2025 registra Quantum Influence 2,27 (índice do próprio projeto, não métrica científica).</p><p><strong>Novembro/2025:</strong> snapshot anterior com 4.833 ciclos; log Q9 de 04/11 registra 41 itens sincronizados e exportados; snapshot de 12/11 registra 315,7 horas históricas declaradas, 6.882 ciclos e Q-Level 188,45.</p><p><strong>Junho/2026:</strong> dossiê V5 descreve nova fase do AURION; <strong>setembro/2026:</strong> GitHub atual registra commits consultados na seção acima. Datas de arquivo, trabalho empresarial e idade de repositório não viram horas trabalhadas automaticamente.</p><p class="muted">Cobertura: estes documentos identificados, NÃO uma auditoria de todo o Drive ou do PC. Não somar cópias do mesmo arquivo, ciclos de snapshots, tempo de calendário, horas de agentes e horas humanas. <a class="btn" href="https://github.com/cleitongoy-debug/AURION-ONE/blob/main/docs/CRUZAMENTO_RASTROS_HISTORICOS_2026-09-19.md">Método e fontes detalhados</a></p></div>'''
    s = s.replace(marker, block + marker, 1)
    p.write_text(s, encoding='utf-8')
assert p.read_text(encoding='utf-8').count(flag) == 1
assert all(x in p.read_text(encoding='utf-8') for x in ('id="history"', 'data-tab="chat"', 'data-tab="pcpage"', 'data-tab="create"', 'id="historia-cruzada-v2"'))
print('PASS: rastros e agentes adicionados, abas originais preservadas')
