const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const ctx={};vm.runInNewContext(fs.readFileSync('android/app/src/main/assets/research_eu3.js','utf8'),ctx);
const disk=new Map(),s={getItem:k=>disk.get(k),setItem:(k,v)=>disk.set(k,v)};
let e=ctx.AurionResearchEngine(s),x=e.add('Catálogo','Drive imagem');
assert.equal(e.cycleStatus().observedMs,0);e.start(x.id,0);
for(let t=1000;t<=1200000;t+=1000)e.tick(t);
assert.equal(e.cycleStatus().completed,1);assert.equal(e.cycleStatus().reports.length,1);
assert.equal(e.cycleStatus().reports[0].documented,0);
e.tick(1260000);assert.equal(e.cycleStatus().observedMs,1200000);
e.tick(1261000,false);assert.equal(e.cycleStatus().observedMs,1200000);
e.proof(x.id,'imagem completa','Descrita e conferida',true,1261500);
assert.equal(e.cycleStatus().observedMs,1200500);assert.equal(e.items()[0].milliseconds,1200500);
e=ctx.AurionResearchEngine(s);assert.equal(e.active(),null);assert.equal(e.cycleStatus().completed,1);
assert.equal(e.cycleStatus().reports.length,1);assert.equal(e.cycleStatus().observedMs,1200500);
const backup=e.export();e.restore(backup);assert.equal(e.cycleStatus().observedMs,1200500);
const x2=e.add('Novo','imagem 2');e.start(x2.id,0);e.tick(-1000);assert.equal(e.cycleStatus().observedMs,1200500);
e.tick(0);assert.equal(e.cycleStatus().observedMs,1201500);
const z=JSON.parse(e.exportCycles());assert.equal(z.category,'LAB_LOCAL_OBSERVADO');
assert.equal(z.reports[0].cycle,1);assert.equal(z.intervalMs,1200000);
console.log('PASS 18 assertions: 20-min threshold, sleep exclusion, proof fraction, paused reload, no import double count, receipt export');
