const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve('android/app/src/main/assets'),out=process.env.EU3_QA_OUTPUT||'/tmp/aurion-eu3-qa';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root))return res.end();try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.EU3_CHROMIUM?{executablePath:process.env.EU3_CHROMIUM}:{}),args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1440,height:1080}});await ctx.addInitScript(()=>{window.nativeCalls=[];window.AurionProfiles={status:()=>JSON.stringify({active:'anark',legacy_owner:'anark',people:[{id:'anark',tabs:'',enabled:true}]})};window.AurionAndroid=new Proxy({},{get:(_,name)=>(...args)=>{window.nativeCalls.push([name,args]);if(name==='memoryList')return '[]';if(name==='memoryExport')return '{"records":[]}';if(name==='getDiagnostics')return JSON.stringify({network:'offline',bluetoothEnabled:false,platform:'Android'});if(name==='accountStatus')return '{}';return '{}';}});});const page=await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/index.html');await page.waitForTimeout(700);console.log('PAGE ERRORS',errors);assert.equal(await page.locator('#eu3.active').count(),1);assert.equal(await page.locator('#euTreeSvg .node').count(),10);assert.equal(await page.locator('#euAgents .eu-agent').count(),6);await page.screenshot({path:out+'/EU3-painel-desktop.png',fullPage:true});
// On-screen study, proof and prerequisite unlock.
await page.locator('#euTreeSvg .node').first().click();await page.locator('#euInspector [data-action=start]').click();await page.waitForTimeout(1200);assert.ok(await page.evaluate(()=>aurionEU3Dashboard.engine.items()[0].milliseconds)>0);await page.locator('#euInspector [data-action=proof]').click();await page.fill('#edRange','Documento local / linhas 1-2');await page.fill('#edResult','Recibo de QA apenas; clique, dependência e persistência conferidos em navegador.');await page.check('#edPassed');await page.click('#edSave');assert.equal(await page.evaluate(()=>aurionEU3Dashboard.engine.items()[0].status),'VALIDADO');assert.equal(await page.evaluate(()=>aurionEU3Dashboard.engine.ready(aurionEU3Dashboard.engine.items()[1])),true);await page.reload();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>aurionEU3Dashboard.engine.items()[0].status),'VALIDADO');
await page.locator('[data-eu-view=factory]').first().click();assert.equal(await page.locator('#euMainView [data-legacy]').count(),29);await page.locator('#euMainView [data-legacy=accounts]').click();assert.equal(await page.locator('#accounts.active').count(),1);assert.equal(await page.locator('#euReturnToBase').isVisible(),true);await page.click('#euReturnToBase');assert.equal(await page.locator('#eu3.active').count(),1);
await page.fill('#euChatInput','Qual a situação do USB Sync?');await page.locator('#euChatForm button').click();assert.match(await page.locator('#euChatLog').innerText(),/recibo|Ponte de memória/);await page.click('#euCheckUpdate');assert.equal(await page.evaluate(()=>nativeCalls.some(x=>x[0]==='checkForUpdate')),true);await page.evaluate(()=>aurionUpdateStatus(JSON.stringify({state:'available',message:'QA: versão disponível',version:'7.2.0'})));await page.click('#euInstallUpdate');assert.equal(await page.evaluate(()=>nativeCalls.some(x=>x[0]==='installAvailableUpdate')),true);await page.click('#euImportApk');assert.equal(await page.evaluate(()=>nativeCalls.some(x=>x[0]==='chooseUpdateApk')),true);
const phoneCtx=await browser.newContext({viewport:{width:412,height:915}});await phoneCtx.addInitScript(()=>{window.nativeCalls=[];window.AurionProfiles={status:()=>JSON.stringify({active:'anark',legacy_owner:'anark',people:[{id:'anark',tabs:'',enabled:true}]})};window.AurionAndroid=new Proxy({},{get:(_,name)=>(...args)=>name==='memoryList'?'[]':'{}'});});const phone=await phoneCtx.newPage();await phone.goto('http://127.0.0.1:'+server.address().port+'/index.html');await phone.waitForTimeout(100);await phone.evaluate(()=>scrollTo(0,0));assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await phone.locator('#euGreenCount').textContent(),'2');await phone.screenshot({path:out+'/EU3-painel-POCO.png',fullPage:true});await phone.screenshot({path:out+'/EU3-POCO-primeira-tela.png'});
console.log('PASS EU3 browser: boot, graph, dependency unlock, observed study time, receipt, reload, legacy return, local lookup, updater bridges and mobile overflow. Android physical installation not tested.');await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
