const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const disk=new Map(),storage={getItem:k=>disk.get(k),setItem:(k,v)=>disk.set(k,v)};const ctx={};vm.runInNewContext(fs.readFileSync('android/app/src/main/assets/research_eu3.js','utf8'),ctx);let e=ctx.AurionResearchEngine(storage);let a=e.add('Fonte A','arquivo:1-20'),b=e.add('Teste B','print:2',[a.id]);assert.throws(()=>e.start(b.id,0));e.start(a.id,0);e.tick(1000);e.tick(100000);assert.equal(e.items()[0].milliseconds,1000);assert.throws(()=>e.proof(a.id,'','',true));e.proof(a.id,'1-20','Reproduzido e conferido',true);e.start(b.id,100001);e.tick(101001);e.pause(101501);e=ctx.AurionResearchEngine(storage);assert.equal(e.active(),null);assert.equal(e.items()[1].milliseconds,1500);assert.equal(e.items()[0].status,'VALIDADO');assert.throws(()=>e.add('X','source',['missing']));console.log('PASS: dependency gate, evidence requirement, bounded timer, persistence, paused reload');

const c=e.add('Teste C','documento:3',[b.id]);
e.proof(b.id,'B:1-10','B validado',true);
e.start(c.id,110000);
e.proof(c.id,'C:1-10','C validado',true);
e.proof(a.id,'A:11','contraprova negativa',false);
const byId=id=>e.items().find(x=>x.id===id);
assert.equal(byId(a.id).status,'EXPERIMENTAL');
assert.equal(byId(b.id).status,'REVISAO_PENDENTE');
assert.equal(byId(c.id).status,'REVISAO_PENDENTE');
assert.equal(byId(b.id).receipts.length,1);
assert.equal(byId(c.id).receipts.length,1);
assert.throws(()=>e.start(c.id,120000));
e=ctx.AurionResearchEngine(storage);
assert.equal(byId(c.id).status,'REVISAO_PENDENTE');
e.proof(a.id,'A:12','revalidado',true);
assert.equal(byId(b.id).status,'REVISAO_PENDENTE');
e.start(b.id,121000);
e.proof(b.id,'B:12','revalidado',true);
assert.equal(byId(c.id).status,'REVISAO_PENDENTE');
e.start(c.id,122000);
e.proof(c.id,'C:12','revalidado',true);
assert.equal(byId(c.id).status,'VALIDADO');
const persisted=JSON.parse(storage.getItem('aurion_eu3_research_v1'));
persisted.items.find(x=>x.id===a.id).status='EXPERIMENTAL';
storage.setItem('aurion_eu3_research_v1',JSON.stringify(persisted));
e=ctx.AurionResearchEngine(storage);
assert.equal(byId(b.id).status,'REVISAO_PENDENTE');
assert.equal(byId(c.id).status,'REVISAO_PENDENTE');
console.log('PASS: transitive counterproof, receipts kept, revalidation, restart and stale data repair');
