plugins { id 'com.android.application' }
android {
    namespace 'one.aurion.app'
    compileSdk 35
    defaultConfig {
        applicationId 'one.aurion.mobile.fixed'
        minSdk 26
        targetSdk 35
        versionCode 21
        versionName '2.1.0'
        manifestPlaceholders = [appLabel: 'AURION ONE MOBILE FIXO']
    }
}
