plugins { id 'com.android.application' }
android {
    namespace 'one.aurion.app'
    compileSdk 35
    defaultConfig {
        applicationId 'one.aurion.morph.node'
        minSdk 26
        targetSdk 35
        versionCode 80
        versionName '8.0.0'
        manifestPlaceholders = [appLabel: 'AURION MORPH NODE']
    }
}
dependencies {
    implementation 'androidx.documentfile:documentfile:1.0.1'
}
